### ISSUE TITLE
[BUG]something error

### ISSUE THREAD

**Issue by lijinhong11** [PojavLauncherTeam/PojavLauncher#786] opened 2021-02-02 09:47 UTC
**Describe the bug**
Can't run any game versions

**To Reproduce**
1. Start PojavLauncher
2. Click the run game button
3. Wait game start
4. An error occurred(l don't know ls runtime pack or pojavlauncher's probblem)

**Screenshots**
 No have
**Platform:**
 - Device Model Huawei enjoys 10
 - CPU architecture aarch64
 - Android Version 9

<details> <summary><b>Error log is here</b></summary>
<br>
<pre>
java.io.FileNotFoundException: /data/user/0/net.kdt.pojavlaunch/jre_runtime/release (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.io.FileReader.<init>(FileReader.java:58)
	at net.kdt.pojavlaunch.utils.JREUtils.readJREReleaseProperties(JREUtils.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:881)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2300(BaseMainActivity.java:26)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:679)
	at java.lang.Thread.run(Thread.java:784)
</pre>
</details>

**Comment by Zeyrox1090** [comment] 2021-02-02 10:14
put error log so devs can see

**Comment by lijinhong11** [comment] 2021-02-02 10:17
Starting pojavlauncher will pop up such an error log:
org.tukaani.xz.CorruptedInputException: Compressed data is corrupt
	at org.tukaani.xz.lz.LZDecoder.repeat(Unknown Source:68)
	at org.tukaani.xz.lzma.LZMADecoder.decode(Unknown Source:78)
	at org.tukaani.xz.LZMA2InputStream.read(Unknown Source:71)
	at org.tukaani.xz.BlockInputStream.read(Unknown Source:8)
	at org.tukaani.xz.SingleXZInputStream.read(Unknown Source:90)
	at org.apache.commons.compress.compressors.xz.XZCompressorInputStream.read(Unknown Source:2)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(Unknown Source:34)
	at java.io.InputStream.read(InputStream.java:101)
	at org.apache.commons.io.IOUtils.copyLarge(Unknown Source:2)
	at org.apache.commons.io.IOUtils.copyLarge(Unknown Source:4)
	at org.apache.commons.io.IOUtils.copy(Unknown Source:0)
	at net.kdt.pojavlaunch.PojavLoginActivity.uncompressTarXZ(PojavLoginActivity.java:600)
	at net.kdt.pojavlaunch.PojavLoginActivity.initMain(PojavLoginActivity.java:412)
	at net.kdt.pojavlaunch.PojavLoginActivity.access$500(PojavLoginActivity.java:75)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:185)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:120)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

**Comment by lijinhong11** [comment] 2021-02-02 10:19
> put error log so devs can see

java.io.FileNotFoundException: /data/user/0/net.kdt.pojavlaunch/jre_runtime/release (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.(FileInputStream.java:165)
	at java.io.FileInputStream.(FileInputStream.java:112)
	at java.io.FileReader.(FileReader.java:58)
	at net.kdt.pojavlaunch.utils.JREUtils.readJREReleaseProperties(JREUtils.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:881)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2300(BaseMainActivity.java:26)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:679)
	at java.lang.Thread.run(Thread.java:784)

**Comment by lijinhong11** [comment] 2021-02-02 10:22
overhead information:
launcher version:3.3.1.1

**Comment by khanhduytran0** [comment] 2021-02-02 10:24
> Compressed data is corrupt

**Comment by khanhduytran0** [comment] 2021-02-02 10:24
Please give us info about build date

**Comment by lijinhong11** [comment] 2021-02-02 10:31
> Please give us info about build date

There is no crash log

**Comment by khanhduytran0** [comment] 2021-02-02 10:31
🤦‍♂ 

I mean the version build date.

**Comment by lijinhong11** [comment] 2021-02-02 10:32
> Please give us info about build date

jre9-aarch64-20200920.tar.xz

**Comment by khanhduytran0** [comment] 2021-02-02 10:33
- Don't use JRE9 or you want bad performance. Use JRE8 instead.

**Comment by lijinhong11** [comment] 2021-02-02 10:36
> * Don't use JRE9 or you want bad performance. Use JRE8 instead.

Where is the runtime pack?Can you give me a link？
I want to try JRE8

**Comment by lijinhong11** [comment] 2021-02-02 10:38
> * Don't use JRE9 or you want bad performance. Use JRE8 instead.
I want to try jre8

**Comment by khanhduytran0** [comment] 2021-02-02 11:08
Use the 60mb apk

**Comment by lijinhong11** [comment] 2021-02-02 12:10
> Use the 60mb apk

I don't know you mean

**Comment by F0x06** [comment] 2021-02-02 13:44
> > Use the 60mb apk
> 
> I don't know you mean

This one with libraries included: https://github.com/PojavLauncherTeam/PojavLauncher/releases/download/v3.3.1.1/app-debug.apk

**Comment by lijinhong11** [comment] 2021-02-03 00:25
> > > Use the 60mb apk
> > 
> > 
> > I don't know you mean
> 
> This one with libraries included: https://github.com/PojavLauncherTeam/PojavLauncher/releases/download/v3.3.1.1/app-debug.apk

This is what I downloaded

**Comment by lijinhong11** [comment] 2021-02-03 00:30
> Use the 60mb apk

I can install arm64, but I will not respond when I run 1.16.4.

**Comment by Mathias-Boulay** [comment] 2021-06-04 19:55
The issue is no more with the google play release.
Closing the issue.

**Closed as completed by Mathias-Boulay** 2021-06-04 19:55 UTC
Labels: bug
