### ISSUE TITLE
[BUG] <When playing for no reason, the game suddenly stops>

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2644] opened 2022-01-29 10:17 UTC
### Describe the bug

When playing for no reason, the game suddenly stops
The game runs smoothly but then hangs for a while and suddenly stops even when playing on the server, but does not generate any reports and logs and I can not send it
Settings and game and launcher version: The latest version of GitHub Actions and Minecraft Forge 1.12.2 with ViaForge mods without Optifine and optimizer. 60% screen quality without jvm manipulation and access to 5 GB of RAM and lower values ​​tested.
Thank you so much❤

### The log file and images/videos

empty

### Steps To Reproduce

```markdown
1.Launch run
1.Login to the server and play
Complete and correct execution of the game and map and server for a few minutes
2.It has a little lag when loading the chunks
3.The game closes with a code 1 warning
4.There are no reports, information or logs
```

### Expected Behavior

Crash when playing

### Platform

```markdown
- Device model: Poco X3 Gt
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: Actions Github
```

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:30
The issue is most likely fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:30 UTC
Labels: bug
