### ISSUE TITLE
on chromebook All the textures are Black and blank.

### ISSUE THREAD

**Issue by Lionboyaz98** [PojavLauncherTeam/PojavLauncher#5709] opened 2024-06-29 12:56 UTC
### Describe the bug

Yeah so on chromebook All the textures are Black and blank. I dont know why this is happening. Ive been using Pojav for over a year and this is SO WEIRD. Pls fix this it makes the game unplayable.

### The log file and images/videos

![Screenshot 2024-06-29 5 39 50 PM](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174189766/45b9dd5e-8fbd-4ebe-8ead-42ae8a22fee7)

### Steps To Reproduce

```markdown
Start pojav launcher... thats it
```

### Expected Behavior

Almost every texture is black (ONLY ON CHROMEBOOK)

### Platform

```markdown
- Device model: CHromebook
- Android version: idk
- PojavLauncher version: 1
```

**Comment by DragonGamer2147** [comment] 2024-06-29 13:48
I am also getting the same error. I reinstalled pojav more than 20 times hoping that the texture would be back but nothing everything is still back and white pjojav devs I request you to fix this bug as quickly as possible. I wasn't getting this error before pojav updated on July 21st

**Comment by DragonGamer2147** [comment] 2024-06-29 18:17
I found a solution, you can use zink renderer and it fixes the bug

**Comment by GaucovyAero** [comment] 2024-06-29 19:08
duplicate of #5674

**Closed as not planned by GaucovyAero** 2024-06-29 19:08 UTC
Labels: bug

**Comment by Camara23ts** [comment] 2024-06-30 11:37
The error is olny for chromebook, Pojav update and have problem with this, the only solution is waiting for a new update or someone solve it

**Comment by Camara23ts** [comment] 2024-06-30 11:41
> x

Explain it

**Comment by Chris1235057** [comment] 2024-07-05 00:14
does anybody know how to fix though

**Comment by Lionboyaz98** [comment] 2024-07-10 10:51
> I found a solution, you can use zink renderer and it fixes the bug

How do you use a different renderer???
