### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Sleepylkelvin** [PojavLauncherTeam/PojavLauncher#2673] opened 2022-02-03 23:48 UTC
### Describe the bug

I installed epic fight mod and epic knights I created a brand new world and when creating it the game says *Game Exit*  I tried

### The log file and images/videos

![Screenshot_20220203-193534_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/98976255/152447191-0fa36bf5-f84c-4dab-81f3-578997014a0e.jpg)

### Steps To Reproduce

```markdown
1 starts pojavluncher with forge
2 load game
3 select world
4 loading world
5 game crashes
```

### Expected Behavior

I expected the game to go in smoothly and perfect

### Platform

```markdown
- Device model: SamsungA20
- CPU architecture: armv8-A
- Android version: 11
- PojavLauncher version:crocus-326-b85dd1620-profiles-2-electrical-boogaloo
```

### Anything else?

I really need to fix this I've been playing mod for 1 month and figuring out how to sign in pojav never give up

**Comment by khanhduytran0** [comment] 2022-02-04 00:15
Please send latestlog.txt

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:33
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:33 UTC
Labels: bug
