### ISSUE TITLE
[BUG] a1.1.1 doesn't work

### ISSUE THREAD

**Issue by Lilith-Crimeow** [PojavLauncherTeam/PojavLauncher#1612] opened 2021-07-02 17:49 UTC
### Describe the bug
Alpha 1.1.1 doesn't work, it's stuck at the purple mojang screen

**Add a log file if you want to see your bug fixed !**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6756227/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Download the a1.1.1 version folder
2. Start PojavLauncher
3. Launch a1.1.1
4. Bug

### Expected behavior:
I expected it to load

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*
![Screenshot_20210702-203343_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/80209203/124311504-8a6daf00-db76-11eb-89ae-172b8582fc93.jpg)

**Platform:**
 - Device Model : Samsung Galaxy Tab s5e
 - CPU architecture : aarch64
 - Android Version : 10
 - PojavLauncher Version : https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/986083769

CriticalRange, a moderator on the Discord server said that a1.1.1 doesn't load, and then sent me the version folder. I tried it and, like he said, it was bugged

**Comment by CriticalRange** [comment] 2021-07-02 18:14
I can reproduce as well
Just noticed he mentioned me lol

**Comment by CriticalRange** [comment] 2021-07-02 19:46
[a1.1.1.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/6756697/a1.1.1.zip)
The file i sent, here if you want to try!

**Comment by Mathias-Boulay** [comment] 2021-07-28 13:20
From the duplicate #1740 
### Describe the bug

Alpha 1.1.1 has a gray screen fix that requires it to use its own lwjgl, but it gets overwritten by pojav's lwjgl, which breaks the game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6893222/latestlog.txt)
![Screenshot_2021-07-28-15-36-22-136_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/77941826/127326194-adc590f1-7928-42ee-a7d3-ce0a2f2d80b4.jpg)


### Steps To Reproduce

```markdown
1. Grab the alpha 1.1.1 jar and normal or grayscreen fix .json from archive.org
2. load alpha 1.1.1 in pojav, like any other custom version
3. watch it get stuck at the blue loading screen
```


### Expected Behavior

I expect the game to either load normally or throw me a gray screen (a well known issue with a1.1.1)

### Platform

```markdown
- Device model: Redmi Note 8 pro
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: v3.3.1.1-937-7ab675e0-
```


### Anything else?

Usually Alpha 1.1.1 loads in a gray screen on some graphics cards, reason why it was up for such a short time and why it was so hard to find. A grayscreen patch json was made but it doesn't work because read above

**Comment by Mathias-Boulay** [comment] 2021-08-19 10:16
The issue is fixed on newer dev builds

**Closed as completed by Mathias-Boulay** 2021-08-19 10:16 UTC
Labels: bug
