### ISSUE TITLE
the mouse support is not working[BUG] <Short description>

### ISSUE THREAD

**Issue by paulopvw** [PojavLauncherTeam/PojavLauncher#1927] opened 2021-08-29 12:29 UTC
### Describe the bug

The mouse doesn't work in the inventory or in the settings and it doesn't have to move the viewThe mouse doesn't work in the inventory or in the settings and it doesn't have to move the view 

### The log file and images/videos

(Video showing the bug)https://youtu.be/XMCPpWVrdJo

### Steps To Reproduce

```markdown
1. Conecte um mouse (🖱️) via Bluetooth
 2. Abra o Pojav Launcher
 3. Inicie qualquer versão do Minecraft
 4. Abra qualquer mundo
 5. Tente olhar ao redor do mundo com o mouse
```

### Expected Behavior

That the mouse supports all modes and I was able to move the view

### Platform

```markdown
- Device model: Asus Max shot/32G
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: latest version of the site
```

**Comment by khanhduytran0** [comment] 2021-08-29 13:16
Duplicate of #1921, which was 3rd(?) issue in the list. Have you ever tried to find the same issue?

**Comment by khanhduytran0** [comment] 2021-08-29 13:17
Duplicate of #1884

**Closed as completed by khanhduytran0** 2021-08-29 13:16 UTC
Labels: bug, duplicate

**Comment by paulopvw** [comment] 2021-08-29 13:29
I reported why this problem is happening to me I didn't try to find the problem
