### ISSUE TITLE
[BUG] It kicks me out of the game when creating a world in 1.12.2

### ISSUE THREAD

**Issue by Kainexx** [PojavLauncherTeam/PojavLauncher#2724] opened 2022-02-10 23:02 UTC
### Describe the bug

It takes me out of the game and then I get a llibrari.jar error that is necessary for a mod

### The log file and images/videos

![Uploading Screenshot_2022-02-07-08-46-38-783_net.kdt.pojavlaunch.jpg…]()

### Steps To Reproduce

```markdown
Solo me salta al crear un mundo en el forge para la 1.12.2 con mods
```

### Expected Behavior

Que lo arreglaran o me dieran información de lo que sucede 

### Platform

```markdown
- Device model: poco x3 pro
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: última versión
```

**Comment by khanhduytran0** [comment] 2022-02-11 01:37
Duplicate of #2679

**Closed as completed by khanhduytran0** 2022-02-11 01:37 UTC
Labels: bug

**Comment by khanhduytran0** [comment] 2022-02-11 01:40
Although latestlog.txt is not provided, we assume that you didn’t login with an online account. Some other informations are also either incomplete or not written in English.

**Comment by UltimateLegend09** [comment] 2023-12-02 06:24
> Although latestlog.txt is not provided, we assume that you didn’t login with an online account. Some other informations are also either incomplete or not written in English.

We have to buy the account What is difference between paid game or pojavluncher
