### ISSUE TITLE
Hope to support the login account of "authlib injector"

### ISSUE THREAD

**Issue by HIM049** [PojavLauncherTeam/PojavLauncher#2014] opened 2021-09-11 12:12 UTC
### Describe the request.

I hope that the launcher can log in using "authlib injector". Many servers are using this account.
This is the github page of "authlib injector": https://github.com/yushijinhun/authlib-injector/

### Anything else?

No others

**Comment by khanhduytran0** [comment] 2021-09-25 01:17
Duplicate of #824

**Closed as completed by khanhduytran0** 2021-09-25 01:17 UTC
Labels: duplicate, enhancement

**Comment by HIM049** [comment] 2021-09-27 15:31
OK, I know. Thanks
