### ISSUE TITLE
Place modpack

### ISSUE THREAD

**Issue by EXOLINE03** [PojavLauncherTeam/PojavLauncher#5753] opened 2024-07-06 01:01 UTC
### Is this request related to a bug?

No

### Describe the request.

There is some way to place modpacks (e.g. the ones that have to be imported into curseforge or the ones that are not in the pojav modpack list) without having to place the mods one by one and place the curseforge profile config

### Anything else?

T

**Comment by GaucovyAero** [comment] 2024-07-06 06:47
duplicate of #5555

**Closed as not planned by GaucovyAero** 2024-07-06 06:47 UTC
Labels: enhancement
