### ISSUE TITLE
[BUG] Entities and transparent assets turn black

### ISSUE THREAD

**Issue by Monke4321** [PojavLauncherTeam/PojavLauncher#2625] opened 2022-01-27 09:06 UTC
### Describe the bug

![2022-01-27_09 01 18](https://user-images.githubusercontent.com/98518881/151326221-e61f02ad-8653-41de-b942-d61eb902b58c.png)
This is the black entities error
Sadly I dont have the clip of the keyboard error.

### The log file and images/videos

![2022-01-27_09 01 18](https://user-images.githubusercontent.com/98518881/151326882-dc5cd3b4-f067-4210-9870-f1e40222632c.png)

### Steps To Reproduce

```markdown
You have to select opengl 1.4 or 1.5 on a fresh installation of mc 1.8 or 1.8.9

Then open any singleplayer world or multiplayer (depends on client) and give damage to any mob or take damage in survival mode.
```

### Expected Behavior

I expect for all the transparent items held in hand and the mob's face to become black

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

No ma'am

**Comment by khanhduytran0** [comment] 2022-01-27 11:56
Have you tried switching back to OpenGL 2.0 with gl4es’s VBO disabled?

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:25
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:25 UTC
Labels: bug
