### ISSUE TITLE
[BUG] Crash On Every Version and While Installing Optfine.Jar

### ISSUE THREAD

**Issue by NotBunnyXD** [PojavLauncherTeam/PojavLauncher#3839] opened 2023-01-11 08:35 UTC
### Describe the bug

I just downloaded pojavlauncher, changed some settings, installed 1.16.5 then I tried to open the game it crashed and showed this message
![20230111_140140](https://user-images.githubusercontent.com/118003242/211756606-d3b472ef-5325-47e0-a747-6afacd887635.jpg)

I tried to install optfine , selected optfine.jar and the same happened.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10390243/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Select any version
3. Launch it
4. Game Crashes
```

### Expected Behavior

I expected game to launch and show MOJANG screen

### Platform

```markdown
- Device model: Samsung Galaxy J7 NXT (7 years old)
- CPU architecture: armv8l
- Android version: 9
- PojavLauncher version: Latest (Playstore)
```

**Comment by GaucovyAero** [comment] 2023-01-24 17:33
1. make sure your screen is rotated into landscape mode
2. have at most about 800-900MB RAM allocated
3. Don't download mods/jars with Chrome, use Firefox
4. Make sure "check libraries after downloading" in pojav is enabled

**Comment by GaucovyAero** [comment] 2023-01-25 09:47
Closing as this is not really a fixable issue and the problem is on your side. The optifine installer works, no doubt about it.

**Closed as not planned by GaucovyAero** 2023-01-25 09:47 UTC
Labels: bug, duplicate
