### ISSUE TITLE
What the why did you update the Pojavlauncher on Google play the zink is not working now on my phone

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#5658] opened 2024-06-23 10:00 UTC
### Describe the bug

The zink on Google play are crash now on my Mali phone pls downgrade the Pojavlauncher on Google play or give to me that version Pojavlauncher last update on Google play I can't play any mod or Modpacks on that update 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15944052/latestlog.txt)

### Steps To Reproduce

```markdown
1. Auto update the Pojavlauncher 
2. Zink crash on my phone now
```

### Expected Behavior

Plss give me that version of Pojavlauncher last update I want to play Modpacks without zink can't play any Modpacks 

### Platform

```markdown
- Device model: Poco c65
- CPU architecture: 64
- Android version: android 14 / 8gb/250gb
- PojavLauncher version: latest on Google request the last update need
```

### Anything else?

Downgrade the update on Google play or give the working zink on Mali plss

It's ruin the game because of that update on Google play

**Comment by kedrick021** [comment] 2024-06-23 10:28
I can't use any update Pojavlauncher render except holygl4es most of mods need opengl 4.+ Or shader support 


And I don't use holygl4es because non of the most Modpacks are working is 1.12.2 like lite Modpacks

**Comment by Marshall2439** [comment] 2024-06-23 13:19
I hate this sht man they just neglect other renderers ik it's device specific stuff but....

**Comment by Legna1104** [comment] 2024-06-23 22:13
X2 el único renderizado que me funcionaba era el zink vulkan y ahora que lo actualize no deja ni iniciar el pojav, se me traba la pantalla y hasta reinicia mi teléfono :(

**Comment by GaucovyAero** [comment] 2024-06-24 08:08
duplicate of #5653

**Closed as not planned by GaucovyAero** 2024-06-24 08:08 UTC
Labels: bug
