### ISSUE TITLE
Cant launch 1.18.1

### ISSUE THREAD

**Issue by Andrey1008** [PojavLauncherTeam/PojavLauncher#2671] opened 2022-02-03 17:18 UTC
### Describe the bug

Aplication exited with code -1

### The log file and images/videos

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2/3/22, 5:12 PM
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at epe.a(SourceFile:423)
	at epe.a(SourceFile:407)
	at dxo.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:199)
Caused by: yk: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at yk.a(SourceFile:48)
	at epw.<init>(SourceFile:200)
	at epe.a(SourceFile:419)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at dry.b(SourceFile:72)
	at dry.a(SourceFile:54)
	at epw.a(SourceFile:241)
	at epw.<init>(SourceFile:182)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at epe.a(SourceFile:423)
	at epe.a(SourceFile:407)
	at dxo.<init>(SourceFile:617)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:199)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (arm) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 247556992 bytes (236 MiB) / 994050048 bytes (948 MiB) up to 994050048 bytes (948 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: ARMv8 Processor rev 4 (v8l)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3938.15
	Virtual memory used (MB): 3189.87
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 411.19
	JVM Flags: 2 total; -Xms948M -Xmx948M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x ARMv8 Processor rev 4 (v8l)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2.launch 1.18.1
```

### Expected Behavior

I expect the game to launches

### Platform

```markdown
- Device model: redmi 9c
- CPU architecture: arm
- Android version: 10
- PojavLauncher version: Google play version
```

### Anything else?

New assets v0 installed.

**Comment by SprainedSpark89** [comment] 2022-02-03 18:40
try 1.17 if that doesn't work you need at least java 16 to run 1.17 or above

**Comment by Andrey1008** [comment] 2022-02-03 19:43
> try 1.17 if that doesn't work you need at least java 16 to run 1.17 or above

Java 17 already installed.

**Comment by SprainedSpark89** [comment] 2022-02-03 21:01
ok

**Comment by SprainedSpark89** [comment] 2022-02-03 21:06
try to turn off VBOs use a older version like 1.17 or 1.16 then launch 1.18.1

**Comment by SprainedSpark89** [comment] 2022-02-03 21:07
found errors ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
try reinstalling 1.18.1

**Comment by Andrey1008** [comment] 2022-02-03 21:26
> found errors ERROR: 0:7: 'max' : cannot redeclare or overload built-in function ERROR: main() function is missing. try reinstalling 1.18.1

1.16.5 working fine, 1.17.1 crashing on mojang loading screen with exit code -1, 1.18.1 crashing after 10-15 seconds after starting also with exit code -1.
Reinstall 1.18.1 - still crashing.

**Comment by Andrey1008** [comment] 2022-02-03 21:29
> try to turn off VBOs use a older version like 1.17 or 1.16 then launch 1.18.1

How i can turn off VBO?

**Comment by SprainedSpark89** [comment] 2022-02-03 22:35
minecraft setting vbos off

**Comment by SprainedSpark89** [comment] 2022-02-03 22:36
empty java arguments

**Comment by SprainedSpark89** [comment] 2022-02-03 22:40
and what render are you using

**Comment by Andrey1008** [comment] 2022-02-03 22:57
> empty java arguments

Already empty, gl4es 1.1.5

**Comment by khanhduytran0** [comment] 2022-02-04 01:59
Try updating to latest actions build.

**Comment by SprainedSpark89** [comment] 2022-02-04 19:31
and try a different render

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:33
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:33 UTC
Labels: bug

**Comment by zhubinsheng** [comment] 2023-05-08 09:26
> 该问题已在候选发布版本中修复。

Excuse me, how did fix it
