### ISSUE TITLE
[BUG] <Short description> When I log in with my Microsoft account it gives me an error 

### ISSUE THREAD

**Issue by Nikogamer489** [PojavLauncherTeam/PojavLauncher#3706] opened 2022-11-19 14:30 UTC
### Describe the bug

Code 1

### The log file and images/videos

Nope

### Steps To Reproduce

```markdown
Start pojavlauncher 
I try to login with microsoft 
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:288)
	at com.kdt.mcgui.mcAccountSpinner.onItemSelected(mcAccountSpinner.java:150)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:1397)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1386)
	at android.widget.AdapterView.access$300(AdapterView.java:61)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1344)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Expected Behavior

Crash

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Medoki** [comment] 2022-11-19 15:16
Same thing here:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.LauncherActivity}: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3731)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8317)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at net.kdt.pojavlaunch.LauncherActivity.onCreate(LauncherActivity.java:155)
	at android.app.Activity.performCreate(Activity.java:8146)
	at android.app.Activity.performCreate(Activity.java:8130)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3700)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2328)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8317)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:288)
	at com.kdt.mcgui.mcAccountSpinner.reloadAccounts(mcAccountSpinner.java:241)
	at com.kdt.mcgui.mcAccountSpinner.init(mcAccountSpinner.java:133)
	at com.kdt.mcgui.mcAccountSpinner.<init>(mcAccountSpinner.java:53)
	... 28 more
Model:
oppo a74 5g : CPH2197
Cpu: qualcomm snapdragon octa-core
android: 11
launcher version: latest gplay

**Comment by Mathias-Boulay** [comment] 2022-11-22 23:00
Should be fixed in the current dev build

**Closed as completed by Mathias-Boulay** 2022-11-22 23:00 UTC
Labels: bug
