### ISSUE TITLE
[BUG] <Short description> pojavlauncher right side of area not working while connected to mouse in Android 14 even tho having optical mouse

### ISSUE THREAD

**Issue by Frozensidxd** [PojavLauncherTeam/PojavLauncher#5530] opened 2024-06-04 12:13 UTC
### Describe the bug

The right side of area in my mobile is not working in pojavlauncher only in pojavlauncher but in other apps it's working correctly even tho I have an optical mouse they said that it will not work on physical mouse but I have optical mouse still not working 
pls help

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/171687467/a9375f7d-43e8-4dc8-b119-56d8c97b54e6
![IMG_20240604_165316](https://github.com/PojavLauncherTeam/PojavLauncher/assets/171687467/d7625264-fcff-44a4-9647-0c9a5214d817)
![IMG_20240604_165250](https://github.com/PojavLauncherTeam/PojavLauncher/assets/171687467/94ef3a2a-b8aa-4f3f-8448-ccaafc13e567)

### Steps To Reproduce

```markdown
I actually don't know what's the problem pls help
```

### Expected Behavior

They said that the right side of area will not work in pojavlauncher if we have physical mouse but I have optical mouse but still not working 

### Platform

```markdown
- Device model: IQ NEO 7 PRO
- CPU architecture: CPU Architecture : 1 x 3.00 GHz
3 x 2.50 GHz
4 x 1.80 GHz
- Android version: 14
- PojavLauncher version: Not working in any version
```

### Anything else?

Pls help

**Comment by Frozensidxd** [comment] 2024-06-04 12:23
Reopen

**Comment by GaucovyAero** [comment] 2024-06-05 08:32
duplicate of #5000

**Closed as not planned by GaucovyAero** 2024-06-05 08:32 UTC
Labels: bug
