### ISSUE TITLE
pojavlauncher in this new foxglove update has a texture bug every time I add mods to the game the texture becomes black and dark at the same time please fix this[BUG] <Short description>

### ISSUE THREAD

**Issue by Daviliraushs** [PojavLauncherTeam/PojavLauncher#5715] opened 2024-06-30 03:18 UTC
### Describe the bug

pojavlauncher in this new foxglove update has a texture bug every time I add mods to the game the texture becomes black and dark at the same time please fix this
![Screenshot_20240630-000838_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/bc6603b1-ac75-4ab3-8efd-6cd8126e5bd3)

### The log file and images/videos

![Screenshot_20240630-000823_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/95861b62-c591-4ff3-8de2-dcd13f3d346f)

### Steps To Reproduce

```markdown
please fix this from pojavlauncher for the love of god bug texture black
```

### Expected Behavior

![Screenshot_20240630-000838_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/3fb2f554-5063-41cd-b11e-8fadf74126c0)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

![Screenshot_20240630-000823_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/128242369/ea93eb70-2ce4-444f-90a9-b7b839c80488)

**Comment by hiimabignoobwihenolive** [comment] 2024-06-30 07:00
The new update i think removed the fix for blackout for powervr. you can use the older versions or use the old fix but the hit color mod is pretty weird and may be something sus so i just recommend you downgrade the pojav version

**Comment by hiimabignoobwihenolive** [comment] 2024-06-30 07:49
This is how you do the old fix
[powervr_ge8320_workaround.txt](https://github.com/user-attachments/files/16043629/powervr_ge8320_workaround.txt)

**Comment by Camara23ts** [comment] 2024-06-30 11:43
> This is how you do the old fix [powervr_ge8320_workaround.txt](https://github.com/user-attachments/files/16043629/powervr_ge8320_workaround.txt)

Its a tutorial with .txt???

**Comment by hiimabignoobwihenolive** [comment] 2024-06-30 11:48
> > This is how you do the old fix [powervr_ge8320_workaround.txt](https://github.com/user-attachments/files/16043629/powervr_ge8320_workaround.txt)
> 
> Its a tutorial with .txt???

Yeah

**Comment by hiimabignoobwihenolive** [comment] 2024-06-30 11:50
I highly recommend to use a prior version because the work around isn't that good

**Comment by Daviliraushs** [comment] 2024-06-30 12:49
Very thanks bro

Em dom., 30 de jun. de 2024 4:00 AM, hiimabignoobwihenolive <
***@***.***> escreveu:

**Comment by GaucovyAero** [comment] 2024-07-01 10:16
duplicate of #5646

**Closed as not planned by GaucovyAero** 2024-07-01 10:16 UTC
Labels: bug
