### ISSUE TITLE
[BUG] Controller inputs crash on latest development build

### ISSUE THREAD

**Issue by EeveeEuphoria** [PojavLauncherTeam/PojavLauncher#2217] opened 2021-11-08 13:53 UTC
### Describe the bug

I'm trying to use my Razer Kishi with this, but any time I so much as press a button when in the java environment, the game immediately crashes. The game works just fine if I'm not using it, or if it's just plugged in and I continue to use touch controls.

I've provided the latestlog, along with the crash log I got and was told to copy when the app closed.

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-105-f26df7edb-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.17.1
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2282
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~9Xt5Nt-PEVHJ75Pfg2h1aA==/net.kdt.pojavlaunch.debug-TTOtpUXdTjnKb9vYwqxBbg==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3
Added custom env: LIBGL_ES=3
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Nov  7 2021 08:33:31
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers is in core ES3, and so used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 128), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Max Color Attachments: 8 / Draw buffers: 8
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
Targeting OpenGL 2.1
NPOT texture handled in hardware
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  (29499): dlopen libgl4es_115.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  (29499): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsctp.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmlib_image.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libextnet.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libinstrument.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/librmi.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/liblcms.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjawt.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libverify.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (29499): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  (29499): dlopen /data/app/~~9Xt5Nt-PEVHJ75Pfg2h1aA==/net.kdt.pojavlaunch.debug-TTOtpUXdTjnKb9vYwqxBbg==/lib/arm64/libopenal.so success
I/jrelog  (29499): Done processing args
I/jrelog  (29499): Found JLI lib
I/jrelog  (29499): Calling JLI_Launch
[13:42:00] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[13:42:00] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[13:42:00] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[13:42:01] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:42:02] [Render thread/INFO]: Setting user: EeveeEuphoria
[13:42:02] [Render thread/WARN]: Invalid floating point value for option textBackgroundOpacity = 
java.lang.NumberFormatException: empty String
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
	at dvt$2.a(SourceFile:408) [1.17.1.jar:?]
	at dvt.a(SourceFile:286) [1.17.1.jar:?]
	at dvt.a(SourceFile:366) [1.17.1.jar:?]
	at dvt.<init>(SourceFile:223) [1.17.1.jar:?]
	at dvp.<init>(SourceFile:459) [1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:179) [1.17.1.jar:?]
[13:42:02] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
DlLoader: using external 
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=29923
EGLBridge: EGLDisplay=0x6f3fa29cd0, EGLSurface=0x6edfb9d020
EGLBridge: Created CTX pointer = 0x6edfba3f80
[13:42:02] [Render thread/INFO]: [STDERR]: java.lang.Exception: Trace exception
[13:42:02] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:1004)
[13:42:02] [Render thread/INFO]: [STDERR]: 	at dpr.<init>(SourceFile:106)
[13:42:02] [Render thread/INFO]: [STDERR]: 	at enx.a(SourceFile:21)
[13:42:02] [Render thread/INFO]: [STDERR]: 	at dvp.<init>(SourceFile:481)
[13:42:02] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:179)
EGLBridge: Comparing: thr=29923, this=0x6edfba3f80, curr=0x0
EGLBridge: Making current on window 0x6edfba3f80 on thread 29923
EGLBridge: eglMakeCurrent() succeed!
[13:42:02] [Render thread/INFO]: [STDOUT]: 6edfba3f80
EGLBridge: Comparing: thr=29923, this=0x6edfba3f80, curr=0x6edfba3f80
[13:42:04] [Render thread/WARN]: ERROR : Couldn't load Narrator library : /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna10956854388351921397.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna10956854388351921397.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
[13:42:04] [Render thread/INFO]: Reloading ResourceManager: Default, assets-v0.zip
[13:42:04] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[13:42:14] [Render thread/INFO]: OpenAL initialized.
[13:42:14] [Render thread/INFO]: Sound engine started
[13:42:14] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[13:42:14] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[13:42:14] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[13:42:14] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[13:42:14] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[13:42:14] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[13:42:14] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:42:17] [Render thread/WARN]: Shader rendertype_text could not find sampler named Sampler2 in the specified shader program.
[13:42:17] [Render thread/WARN]: Shader rendertype_text_intensity could not find sampler named Sampler2 in the specified shader program.
[13:42:19] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[13:42:19] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:42:19] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:42:28] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:42:28] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:42:28] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:42:28] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:42:28] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:42:28] [Render thread/INFO]: Reloading ResourceManager: Default
[13:42:29] [Render thread/INFO]: Loaded 7 recipes
[13:42:30] [Render thread/INFO]: Loaded 1137 advancements
[13:42:34] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:42:34] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[13:42:34] [Server thread/INFO]: Generating keypair
[13:42:44] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:46] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:46] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:47] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:47] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:48] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:48] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:49] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:49] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:50] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:50] [Render thread/INFO]: Preparing spawn area: 0%
[13:42:50] [Render thread/INFO]: Preparing spawn area: 1%
[13:42:51] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:52] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:52] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:55] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:55] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:55] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:55] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:55] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:55] [Render thread/INFO]: Preparing spawn area: 2%
[13:42:55] [Render thread/INFO]: Preparing spawn area: 5%
[13:42:56] [Render thread/INFO]: Preparing spawn area: 6%
[13:42:57] [Render thread/INFO]: Preparing spawn area: 6%
[13:42:57] [Render thread/INFO]: Preparing spawn area: 6%
[13:42:58] [Render thread/INFO]: Preparing spawn area: 6%
[13:42:58] [Render thread/INFO]: Preparing spawn area: 6%
[13:42:58] [Render thread/INFO]: Preparing spawn area: 9%
[13:42:59] [Render thread/INFO]: Preparing spawn area: 9%
[13:43:00] [Render thread/INFO]: Preparing spawn area: 9%
[13:43:00] [Render thread/INFO]: Preparing spawn area: 10%
[13:43:00] [Render thread/INFO]: Preparing spawn area: 10%
[13:43:01] [Render thread/INFO]: Preparing spawn area: 10%
[13:43:01] [Render thread/INFO]: Preparing spawn area: 10%
[13:43:02] [Render thread/INFO]: Preparing spawn area: 10%
[13:43:03] [Render thread/INFO]: Preparing spawn area: 13%
[13:43:03] [Render thread/INFO]: Preparing spawn area: 13%
[13:43:04] [Render thread/INFO]: Preparing spawn area: 14%
[13:43:04] [Render thread/INFO]: Preparing spawn area: 14%
[13:43:05] [Render thread/INFO]: Preparing spawn area: 15%
[13:43:05] [Render thread/INFO]: Preparing spawn area: 16%
[13:43:06] [Render thread/INFO]: Preparing spawn area: 16%
[13:43:06] [Render thread/INFO]: Preparing spawn area: 17%
[13:43:07] [Render thread/INFO]: Preparing spawn area: 17%
[13:43:07] [Render thread/INFO]: Preparing spawn area: 20%
[13:43:08] [Render thread/INFO]: Preparing spawn area: 21%
[13:43:08] [Render thread/INFO]: Preparing spawn area: 22%
[13:43:09] [Render thread/INFO]: Preparing spawn area: 23%
[13:43:09] [Render thread/INFO]: Preparing spawn area: 23%
[13:43:10] [Render thread/INFO]: Preparing spawn area: 24%
[13:43:10] [Render thread/INFO]: Preparing spawn area: 26%
[13:43:10] [Render thread/INFO]: Preparing spawn area: 28%
[13:43:11] [Render thread/INFO]: Preparing spawn area: 29%
[13:43:11] [Render thread/INFO]: Preparing spawn area: 32%
[13:43:12] [Render thread/INFO]: Preparing spawn area: 34%
[13:43:12] [Render thread/INFO]: Preparing spawn area: 34%
[13:43:13] [Render thread/INFO]: Preparing spawn area: 42%
[13:43:13] [Render thread/INFO]: Preparing spawn area: 45%
[13:43:14] [Render thread/INFO]: Preparing spawn area: 46%
[13:43:15] [Render thread/INFO]: Preparing spawn area: 48%
[13:43:15] [Render thread/INFO]: Preparing spawn area: 54%
[13:43:16] [Render thread/INFO]: Preparing spawn area: 56%
[13:43:16] [Render thread/INFO]: Preparing spawn area: 58%
[13:43:16] [Render thread/INFO]: Preparing spawn area: 61%
[13:43:17] [Render thread/INFO]: Preparing spawn area: 64%
[13:43:18] [Render thread/INFO]: Preparing spawn area: 68%
[13:43:18] [Render thread/INFO]: Preparing spawn area: 70%
[13:43:19] [Render thread/INFO]: Preparing spawn area: 73%
[13:43:19] [Render thread/INFO]: Preparing spawn area: 77%
[13:43:19] [Render thread/INFO]: Preparing spawn area: 79%
[13:43:20] [Render thread/INFO]: Preparing spawn area: 82%
[13:43:20] [Render thread/INFO]: Preparing spawn area: 85%
[13:43:21] [Render thread/INFO]: Preparing spawn area: 88%
[13:43:21] [Render thread/INFO]: Preparing spawn area: 90%
[13:43:22] [Render thread/INFO]: Preparing spawn area: 94%
[13:43:23] [Render thread/INFO]: Preparing spawn area: 98%
[13:43:23] [Render thread/INFO]: Time elapsed: 38679 ms
[13:43:23] [Server thread/INFO]: Changing view distance to 2, from 10
[13:43:23] [Render thread/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 0b:de:2c:61:60:e5:6a:da
[13:43:23] [Server thread/INFO]: EeveeEuphoria[local:E:93d93440] logged in with entity id 304 at (-42.5, 66.0, -222.5)
[13:43:23] [Server thread/INFO]: EeveeEuphoria joined the game
[13:43:25] [Server thread/INFO]: Saving and pausing game...
[13:43:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[13:43:25] [Render thread/INFO]: Loaded 0 advancements
[13:43:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[13:43:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[13:43:26] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2596ms or 51 ticks behind
[13:43:40] [Render thread/INFO]: Loaded 4 advancements

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.setInt(java.lang.Object, int)' on a null object reference
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.setDummyEventKeycode(GamepadDpad.java:76)
		at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.convertEvent(GamepadDpad.java:67)
			at net.kdt.pojavlaunch.customcontrols.gamepad.Gamepad.update(Gamepad.java:173)
				at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:618)
					at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
						at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:474)
							at android.view.ViewRootImpl$ViewPostImeInputStage.processGenericMotionEvent(ViewRootImpl.java:6403)
								at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6152)
									at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
										at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
											at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
												at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5814)
													at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
														at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5871)
															at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
																at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
																	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
																		at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
																			at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
																				at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
																					at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
																						at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5847)
																							at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6005)
																								at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3158)
																									at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
																										at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
																											at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3135)
																												at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
																													at android.os.MessageQueue.nativePollOnce(Native Method)
																														at android.os.MessageQueue.next(MessageQueue.java:335)
																															at android.os.Looper.loopOnce(Looper.java:161)
																																at android.os.Looper.loop(Looper.java:288)
																																	at android.app.ActivityThread.main(ActivityThread.java:7839)
																																		at java.lang.reflect.Method.invoke(Native Method)
																																			at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
																																				at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
																																				

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Log in using Microsoft Account
3. Launch 1.17.1 (also tried the default version of 1.7.10)
4. Press any button on the Razer Kishi
5. Crash.

Renderer used: vgpu (OpenGL ES3)
```

### Expected Behavior

I expect the game to not crash?

### Platform

```markdown
- Device model: Pixel 6
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1431054775
```

**Comment by Mathias-Boulay** [comment] 2021-11-08 20:30
Oh oh, I may know what happened

**Comment by Mathias-Boulay** [comment] 2021-11-08 20:32
I'll investigate the issue soon.
Does the issue appears regardless of the button/joystick used first ?

**Comment by EeveeEuphoria** [comment] 2021-11-08 20:33
I don't think it mattered which I did first, a crash would happen about a second after pressing a button or using a joystick

**Comment by Mathias-Boulay** [comment] 2021-11-08 20:34
Okay, thanks for the input @EeveeEuphoria 
Does it happen with any gamepad or just this one ?

**Comment by EeveeEuphoria** [comment] 2021-11-08 20:35
Haven't tested with any other gamepad, don't have them on hand.

**Comment by Mathias-Boulay** [comment] 2021-11-11 16:47
I dropped a new control revision @EeveeEuphoria, can you test it out and see if the issue is still present ?

**Comment by Mathias-Boulay** [comment] 2021-11-24 22:59
fixed on newer dev builds

**Closed as completed by Mathias-Boulay** 2021-11-24 22:59 UTC
Labels: bug
