### ISSUE TITLE
[BUG] erro 1

### ISSUE THREAD

**Issue by Artur135662** [PojavLauncherTeam/PojavLauncher#6185] opened 2024-10-20 23:35 UTC
### Describe the bug

Como resolve isso? 

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240922-a6a6a29-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-A207M
Info: API version: 30
Info: Selected Minecraft version: fabric-loader-0.16.5-1.20.1
Info: Custom Java arguments: ""
--------- beginning of main

--------- beginning of system

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=902
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/~~6_ErzRX2GvYrC3qsPDowxw==/net.kdt.pojavlaunch-1Q7OsOQ0l31b8Oc_ZJjXDA==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~6_ErzRX2GvYrC3qsPDowxw==/net.kdt.pojavlaunch-1Q7OsOQ0l31b8Oc_ZJjXDA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=432
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  (11726): dlopen libgl4es_114.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (11726): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  (11726): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  (11726): dlopen /data/app/~~6_ErzRX2GvYrC3qsPDowxw==/net.kdt.pojavlaunch-1Q7OsOQ0l31b8Oc_ZJjXDA==/lib/arm64/libopenal.so success

I/jrelog  (11726): Done processing args

I/jrelog  (11726): Found JLI lib
I/jrelog  (11726): Calling JLI_Launch

Error: Could not find or load main class net.fabricmc.loader.impl.launch.knot.KnotClient
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient

### Steps To Reproduce

```markdown
1 inicie o javlaucher abra a versão 1.20.1
```

### Expected Behavior

Abrir a versão e jogar

### Platform

```markdown
- Device model: Samsung a20s
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: não sei
```

### Anything else?

Não

**Comment by GaucovyAero** [comment] 2024-10-31 11:42
duplicate of #5657, try using java 21 or use another build of jre17 from android-openjdk-build-multiarch or maybe try finding another jre17 build, dunno

**Closed as not planned by GaucovyAero** 2024-10-31 11:42 UTC
Labels: bug
