### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by chertnavelosipede** [PojavLauncherTeam/PojavLauncher#3888] opened 2023-01-30 04:41 UTC
### Describe the bug

Описание: Пытаюсь уже второй день зайти на сервер вместе с другом, пишет unknown host, остальные сервера работают как надо, ошибок не лезет. Адрес сервера: play.countrymc.net

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.16
--------- beginning of system
--------- beginning of main
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2310
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~XBpzaR6SBdCCslnUJgLnOw==/net.kdt.pojavlaunch-fx4RHiUrV_DeExU7KJts9Q==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
I/LIBGL   (17534): Initialising gl4es
I/LIBGL   (17534): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   (17534): Using GLES 2.0 backend
I/LIBGL   (17534): loaded: libGLESv2.so
I/LIBGL   (17534): loaded: libEGL.so
I/LIBGL   (17534): Using GLES 2.0 backend
I/LIBGL   (17534): Hardware Full NPOT detected and used
I/LIBGL   (17534): FBO are in core, and so used
I/LIBGL   (17534): PointSprite are in core, and so used
I/LIBGL   (17534): CubeMap are in core, and so used
I/LIBGL   (17534): BlendColor is in core, and so used
I/LIBGL   (17534): Blend Substract is in core, and so used
I/LIBGL   (17534): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (17534): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (17534): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (17534): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (17534): Extension GL_OES_depth24  detected and used
I/LIBGL   (17534): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (17534): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (17534): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (17534): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (17534): Extension GL_OES_texture_float  detected and used
I/LIBGL   (17534): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   (17534): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (17534): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (17534): high precision float in fragment shader available and used
I/LIBGL   (17534): Max vertex attrib: 32
I/LIBGL   (17534): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (17534): Max texture size: 16384
I/LIBGL   (17534): Max Varying Vector: 31
I/LIBGL   (17534): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (17534): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (17534): Max Anisotropic filtering: 16
I/LIBGL   (17534): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   (17534): Hardware vendor is Qualcomm
I/LIBGL   (17534): GLSL 300 es supported
I/LIBGL   (17534): GLSL 310 es supported and used
I/LIBGL   (17534): sRGB surface supported
I/LIBGL   (17534): EGLImage to Texture2D supported
I/LIBGL   (17534): EGLImage to RenderBuffer supported
I/LIBGL   (17534): ignore MipMap
I/LIBGL   (17534): Targeting OpenGL 2.1
I/LIBGL   (17534): NPOT texture handled in hardware
I/LIBGL   (17534): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (17534): try to use VBO
I/LIBGL   (17534): glX Will try to recycle EGL Surface
I/LIBGL   (17534): Current folder is:/
I/jrelog  (17534): dlopen libgl4es_114.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (17534): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (17534): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (17534): dlopen /data/app/~~XBpzaR6SBdCCslnUJgLnOw==/net.kdt.pojavlaunch-fx4RHiUrV_DeExU7KJts9Q==/lib/arm64/libopenal.so success
I/jrelog  (17534): Done processing args
I/jrelog  (17534): Found JLI lib
I/jrelog  (17534): Calling JLI_Launch
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

[04:22:32] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[04:22:32] [Render thread/INFO]: Setting user: slave228
[04:22:33] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[04:22:33] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[04:22:33] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[04:22:33] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=17672
EGLBridge: EGLDisplay=0x1, EGLSurface=0x72c95ead80
EGLBridge: Created CTX pointer = 0x72bbc56800
[04:22:33] [Render thread/INFO]: [STDERR]: java.lang.Exception: Trace exception
[04:22:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:1004)
[04:22:33] [Render thread/INFO]: [STDERR]: 	at dgy.<init>(SourceFile:104)
[04:22:33] [Render thread/INFO]: [STDERR]: 	at ecn.a(SourceFile:21)
[04:22:33] [Render thread/INFO]: [STDERR]: 	at dlx.<init>(SourceFile:449)
[04:22:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:177)
EGLBridge: Comparing: thr=17672, this=0x72bbc56800, curr=0x0
EGLBridge: Making current on window 0x72bbc56800 on thread 17672
EGLBridge: eglMakeCurrent() succeed!
[04:22:33] [Render thread/INFO]: [STDOUT]: 72bbc56800
EGLBridge: Comparing: thr=17672, this=0x72bbc56800, curr=0x72bbc56800
[04:22:36] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Native library (linux-aarch64/libfliteWrapper.so) not found in resource path ([file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/jsr305.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-glfw-classes.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-jemalloc.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-openal.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-opengl.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-stb.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-tinyfd.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/lib
raries/com/google/guava/guava/21.0/guava-21.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar, file:/storage/emulated/0/Android/dat
a/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.16/1.16.jar])
[04:22:36] [Render thread/INFO]: Reloading ResourceManager: Default
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[04:22:47] [Render thread/INFO]: OpenAL initialized.
[04:22:47] [Render thread/INFO]: Sound engine started
[04:22:48] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[04:22:48] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[04:22:48] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[04:22:48] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[04:22:48] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[04:22:48] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[04:22:48] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[04:22:49] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[04:22:49] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[04:22:49] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas

### Steps To Reproduce

```markdown
1)Запустил лаунчер;
2)выбрал уч. запись;
3)запустил последнюю выбранную версию;
4)нажал на кнопку многопользоват. игры;
5)информация о сервере обновилась и выдало ошибку: Не удается определить имя хоста, а если нажать на запуск то выдает ошибку: unknown host.
```

### Expected Behavior

Ожидалось что я смогу зайти на сервер без каких либо ошибок.

### Platform

```markdown
- Device model: POCO X3 PRO
- CPU architecture: 
- Android version: 12
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

Друг имеет более новую версию лаунчера и лицензию- он все равно не может зайти. 
Версия: 1.16

**Comment by artdeell** [comment] 2023-01-30 05:29
Лаунчер обнови

**Comment by chertnavelosipede** [comment] 2023-01-30 05:31
Баг не зависит от версии лаунчера, я написал что у друга и более новая версия и лицензия имеется, все равно не работает

**Comment by chertnavelosipede** [comment] 2023-01-30 05:35
Обновил, не помогло

**Comment by GaucovyAero** [comment] 2023-01-30 18:30
duplicate of #3730

**Closed as not planned by GaucovyAero** 2023-01-30 18:30 UTC
Labels: bug, duplicate
