### ISSUE TITLE
[BUG] Mouse bug.

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5669] opened 2024-06-24 08:42 UTC
### Describe the bug

On the same device (2 redmi 20pro) but one is stock rom and one with evolution X rom, the stock rom had this mouse problem. When the mouse is not moving.

### The log file and images/videos

Video:https://drive.google.com/file/d/1vYPMd_yPAndw1mMh3o7LQvR05AWGq_MY/view?usp=drivesdk

No logs, I tested every version and the but is still there.

### Steps To Reproduce

```markdown
N/A
```

### Expected Behavior

Just want mouse to work normally.

### Platform

```markdown
- Device model: 2 k20 pro
- CPU architecture: idk, check the snapdragon 855.
- Android version: one with stock MIUI 12 and one with android 13.
- PojavLauncher version: both are newest.
```

### Anything else?

Both Bluetooth and OTG mouse does not work.

**Comment by GaucovyAero** [comment] 2024-06-24 10:26
duplicate of #5648

**Closed as not planned by GaucovyAero** 2024-06-24 10:26 UTC
Labels: bug

**Comment by TylerHaoNhot** [comment] 2024-06-24 11:05
> duplicate of #5648

I had to downgrade to the 2023/09/27 (randomly choose that) to can play with it. I suggest you to remove the feature that turn the default android mouse to the white pojavlauncher's mouse. Keep it as default make it no issues.

**Comment by TylerHaoNhot** [comment] 2024-06-24 11:06
> duplicate of #5648

Also, can you explain that why the phone with OEM rom run fine with that but the MIUI rom doesn't work?
