### ISSUE TITLE
[F-REQ]Add Java16 and open gl 3.2 please

### ISSUE THREAD

**Issue by Nishu-max** [PojavLauncherTeam/PojavLauncher#1485] opened 2021-06-05 05:55 UTC
**Is your feature request related to a problem? Please describe.**
Please add java 16 and opengl 3.2 .1.17 is releasing on 8 June.I need to play it because tough as nails (my favourite mod)will add new features not needed to view.and also I think that it will remove crashes on many mods and clients like chlorine and aristos
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment] 2021-06-05 06:16
Duplicate of #1476

**Closed as completed** 2021-06-05 06:16 UTC
Labels: duplicate, enhancement
