### ISSUE TITLE
[No Shaders Zink Problem] <Short description>

### ISSUE THREAD

**Issue by Unknown795** [PojavLauncherTeam/PojavLauncher#5769] opened 2024-07-09 11:40 UTC
### Describe the bug

Since the latest Pojav Launcher update on both Google Play Store and GitHub versions, I can no longer play Minecraft with shaders due to the problem with the Zink Renderer on latest updates. 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16142696/latestlog.txt)

### Steps To Reproduce

```markdown
Open Pojav Launcher
Select Zink Vulkan Renderer
Launch any version of Minecraft
The game will immediately crash without showing any error code.
```

### Expected Behavior

The game will launch with the Zink Renderer, and I can play again with shaders. 

### Platform

```markdown
- Device model: Redmi Note 10s
- CPU architecture: arm64 bit
- Android version: 14
- PojavLauncher version: Latest GitHub and Google Play Store versions. (all of the latest versions).
```

### Anything else?

It is not crashing because I use shaders, the game is crashing on its own every time I use Zink Renderer to play Minecraft, but since I use shaders I need zink renderer, and since that's the case, it means no shaders. I really hope you are going to address this issue and fix this as soon as possible, because pojav launcher is really good when it come to playing Minecraft Java Edition on mobile devices.

**Comment by GaucovyAero** [comment] 2024-07-09 19:54
duplicate of #5653

**Closed as not planned by GaucovyAero** 2024-07-09 19:54 UTC
Labels: bug
