### ISSUE TITLE
[BUG] Weird mouse bug

### ISSUE THREAD

**Issue by XDBBXD** [PojavLauncherTeam/PojavLauncher#1253] opened 2021-04-19 16:03 UTC
### Describe the bug
The view during the game is terribly cutting when controlling the physical mouse connected to the phone. On the other hand touchscreen is smooth. Issue appears in every version (modded or vanilla). I tried changing mouses but that didn't fix issue. While playing a long time mouse control might get smoother overtime, but only for a minute.
Trying to document it, screen recording fixes the mouse cutting (but unfortunately only during recording) :( 

(logs before screen record attempt)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6337222/latestlog.txt)
[latestlog_1.12.2.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6337223/latestlog_1.12.2.txt)
[latestlog1.16.5.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6337225/latestlog1.16.5.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Connect peripherals to phone (mouse + keyboard)
2. Start PojavLauncher
3. Pick any version
4. Enter single player world or server
5. Move the mouse

### Expected behavior:
I expected for it to be smooth like the touchscreen (and without having to record the screen while playing)

### Screenshots or videos:
https://youtu.be/qhZ8IZuc_YQ
(Sorry for the quality of the recording. The only second phone that would record the whole phenomenon was Nokia Lumia)

**Platform:**
 - Device Model [Galaxy S20 FE 5G]
 - CPU architecture [aarch64] 
 - Android Version [11]
 - PojavLauncher Version [version 3.3.1.1_rel_20210321]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Interesting behavior
</pre>
</details>

**Comment by khanhduytran0** [comment] 2021-04-19 23:07
Duplicate of #1235

**Comment by Blimyst** [comment] 2021-04-20 09:24
@khanhduytran0 well, can you fix it?

**Comment by khanhduytran0** [comment] 2021-04-20 09:27
I don't have a mouse to debug around this problem... Ask @artdeell

**Comment by Blimyst** [comment] 2021-04-20 10:04
@artdeell umm, can you fix this and mine #1235 ?

**Comment by infinite9898** [comment] 2021-05-30 05:31
Yes go to settings and you can set the size of mouse

**Comment by Mathias-Boulay** [comment] 2021-09-01 11:30
This issue should be fixed on the crocus gplay update
closing

**Closed as completed by Mathias-Boulay** 2021-09-01 11:30 UTC
Labels: bug
