### ISSUE TITLE
[BUG] <Short description> physical mouse not working 

### ISSUE THREAD

**Issue by Akashbhai999** [PojavLauncherTeam/PojavLauncher#5574] opened 2024-06-13 16:26 UTC
### Describe the bug

when I use physical mouse on pojavelauncher then mouse not working on the right side of the screen . My phone's current android version is 14 and my phone is realme 12 plus

### The log file and images/videos

when I use physical mouse on pojavelauncher then mouse not working on the right side of the screen . My phone's current android version is 14 and my phone is realme 12 plus

### Steps To Reproduce

```markdown
when I use physical mouse on pojavelauncher then mouse not working on the right side of the screen . My phone's current android version is 14 and my phone is realme 12 plus
```

### Expected Behavior

when I use physical mouse on pojavelauncher then mouse not working on the right side of the screen . My phone's current android version is 14 and my phone is realme 12 plus

### Platform

```markdown
- Device model: realme 12 plus 5g
- CPU architecture:mediatek dimensity 7050 
- Android version: 14
- PojavLauncher version: Version edelweiss-20230928-9489d0e-w3_openide
```

**Comment by GaucovyAero** [comment] 2024-06-13 20:55
duplicate of #5000

**Closed as not planned by GaucovyAero** 2024-06-13 20:55 UTC
Labels: bug
