### ISSUE TITLE
[BUG]Cant join my friend's modded lan world 

### ISSUE THREAD

**Issue by Nathan12e4** [PojavLauncherTeam/PojavLauncher#6204] opened 2024-10-27 09:25 UTC
### Describe the bug

I Cant Join My Friend's Modded Lan World

### The log file and images/videos

There is no log

### Steps To Reproduce

```markdown
It always do that
```

### Expected Behavior

I expect to join my friend's modded lan world 

### Platform

```markdown
- Device model: 22120RN86G
- CPU architecture: Mediatek Helio G85
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-10-31 11:30
duplicate of #5493

**Closed as not planned by GaucovyAero** 2024-10-31 11:30 UTC
Labels: bug
