### ISSUE TITLE
Bug When My At a Phone that has aarch32

### ISSUE THREAD

**Issue by JohnPrinceDugan** [PojavLauncherTeam/PojavLauncher#2077] opened 2021-09-28 13:24 UTC
### Describe the bug

Any phone that has aarch32 will crash
Past version work properly with aarch32
New version keep crashing
Works with aarch64 and up

### Steps To Reproduce

```markdown
Have a phone that has a aarch 32
Install pojav launcher
Install any version (1.17 not)
After installing play it
BOOM Crash WTF.
```

### Expected Behavior

When i play in any aarch32 phones the pojav crash even in  when i install it from the first time

Before
The pojav launcher works perfectly
After
The new update keep crashing

### Platform

```markdown
- Device model:Samsung j6+ 
- CPU architecture:aarch32
- Android version:10
- PojavLauncher version: latest version from playstore
```

**Comment by khanhduytran0** [comment] 2021-09-28 13:27
Log file is missing.
> *No response*

**Comment by khanhduytran0** [comment] 2021-09-28 13:37
@JohnPrinceDugan reply wen eta? the message just sent 1 minute after your auto ram issue. **if you don't send this issue will be terminated.**

**Comment by NotAHero04** [comment] 2021-09-28 13:39
If you look at the PojavLauncher website, you’ll see this note:
> 32-bit platforms (ARMv7 and i386) is currently broken [...]
>
So, wait for it to be fixed.

**Comment by khanhduytran0** [comment] 2021-09-28 13:48
Duplicate of #2072

**Closed as completed** 2021-09-28 13:48 UTC
Labels: bug, duplicate, NO_LOG
