### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Chris1235057** [PojavLauncherTeam/PojavLauncher#5744] opened 2024-07-04 17:49 UTC
### Describe the bug

My text are blank and my textures are broken

### The log file and images/videos

![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/162224322/88bdd291-652a-4e2d-9b43-207f7b32b187)

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

I should be able to play without a texture problem

### Platform

```markdown
- Device model: acer Chromebook 
- CPU architecture: 
- Android version:idk 
- PojavLauncher version: idk
```

### Anything else?

Black texture

**Comment by Chris1235057** [comment] 2024-07-04 17:49
someone pls help me

**Comment by Protofr** [comment] 2024-07-05 11:55
This is a duplicate, but you need to follow the instructions in this file:
[powervr_ge8320_workaround.txt](https://github.com/user-attachments/files/16109296/powervr_ge8320_workaround.txt)

It does not work for 1.21 as I know. Unless you find a hitbox mod that works for 1.21, please lmk aswell.

**Comment by GaucovyAero** [comment] 2024-07-06 06:54
duplicate of #5674

**Closed as not planned by GaucovyAero** 2024-07-06 06:54 UTC
Labels: bug

**Comment by Chris1235057** [comment] 2024-07-07 19:48
Thanks

**Comment by Chris1235057** [comment] 2024-07-08 14:23
it says that 
I can't install any apk that doesn't come from the playstore
