### ISSUE TITLE
[F-Req] Experimental Resolutions

### ISSUE THREAD

**Issue by Slixxthedev** [PojavLauncherTeam/PojavLauncher#6254] opened 2024-11-10 15:09 UTC
### Is this request related to a bug?

Changing resolution through the resolution scaler changes the mouse alignment to the minecraft GUI which really ruins up the game sometimes, it is much more visible when you attempt to use clients having custom menus.

### Describe the request.

A resolution input box where the user can input custom resolution Ex: `1280` x `720` which will change the game resolution to the given inputs and for the screen size, the remaining screen can be kept intact/black so that the game isn't stretched

### Anything else?

Would like to see these features as experiments since they can easily break the game.

**Comment by GaucovyAero** [comment] 2024-11-10 18:45
duplicate of #4317

**Closed as not planned by GaucovyAero** 2024-11-10 18:45 UTC
Labels: enhancement
