### ISSUE TITLE
I can't open 1.18.1

### ISSUE THREAD

**Issue by FloatAway** [PojavLauncherTeam/PojavLauncher#2634] opened 2022-01-28 00:56 UTC
### Describe the bug

Application exited with code -1

### The log file and images/videos

![Screenshot_2022-01-28-08-56-11-97_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/98564604/151468296-cb47e113-1cbe-4279-805c-1152b3905bd2.jpg)
![Uploading Screenshot_2022-01-28-08-56-10-53_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

### Steps To Reproduce

```markdown
1.Install jre17-arm in pojavlauncher
2.change into gl4es 1.1.5
3.start up pojavlauncher,Appear code:-1 and pojavlauncher was shut down
```

### Expected Behavior

I hope I can play on 1.18.1

### Platform

```markdown
- Device model: oppo Reno z 8/128
- CPU architecture: I don't know how to check this
- Android version: 10
- PojavLauncher version: latest release on 2021/08/31
```

### Anything else?

Please help me

**Comment by FloatAway** [comment] 2022-01-28 00:59
--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.1
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2264
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-tazI93g9H85P54TcuEsXjw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3
Added custom env: LIBGL_ES=3
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Aug 18 2021 16:47:47
Using GLES 2.0 backend
--------- beginning of main
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers is in core ES3, and so used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
Extension GL_OES_fragment_precision_high  detected and used
Extension GL_EXT_shader_texture_lod detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Max texture size: 4096
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Max Color Attachments: 8 / Draw buffers: 8
Hardware vendor is Imagination Technologies
GLSL 300 es supported
GLSL 310 es supported and used
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
Targeting OpenGL 2.1
NPOT texture handled in hardware
Not trying to batch small subsequent glDrawXXXX
try to use VBO
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
[00:07:52] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[00:07:52] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[00:07:52] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[00:07:53] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:07:57] [Render thread/INFO]: Setting user: FloatAway91
[00:07:58] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=11651
EGLBridge: EGLDisplay=0x1, EGLSurface=0x73ecfe3100
EGLBridge: Created CTX pointer = 0x73ecfe3a80
[00:07:58] [Render thread/INFO]: [STDERR]: java.lang.Exception: Trace exception
[00:07:58] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:1004)
[00:07:58] [Render thread/INFO]: [STDERR]: 	at drp.<init>(SourceFile:106)
[00:07:58] [Render thread/INFO]: [STDERR]: 	at eqa.a(SourceFile:21)
[00:07:58] [Render thread/INFO]: [STDERR]: 	at dxo.<init>(SourceFile:476)
[00:07:58] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:199)
EGLBridge: Comparing: thr=11651, this=0x73ecfe3a80, curr=0x0
EGLBridge: Making current on window 0x73ecfe3a80 on thread 11651
EGLBridge: eglMakeCurrent() succeed!
[00:07:59] [Render thread/INFO]: [STDOUT]: 73ecfe3a80
Initialising gl4es
v1.1.5 built on Aug 18 2021 16:47:47
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers is in core ES3, and so used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
Extension GL_OES_fragment_precision_high  detected and used
Extension GL_EXT_shader_texture_lod detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Max texture size: 4096
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Max Color Attachments: 8 / Draw buffers: 8
Hardware vendor is Imagination Technologies
GLSL 300 es supported
GLSL 310 es supported and used
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
Targeting OpenGL 2.1
NPOT texture handled in hardware
Not trying to batch small subsequent glDrawXXXX
try to use VBO
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
EGLBridge: Comparing: thr=11651, this=0x73ecfe3a80, curr=0x0
EGLBridge: Making current on window 0x73ecfe3a80 on thread 11651
EGLBridge: eglMakeCurrent() succeed!
[00:07:59] [Render thread/WARN]: Couldn't get pack info for: java.util.zip.ZipException: zip file is empty
[00:07:59] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it doesn't seem to exist anymore
[00:08:02] [Render thread/WARN]: ERROR : Couldn't load Narrator library : /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna7822855992673336066.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna7822855992673336066.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch/runtimes/jdk17-arm64-20210825-release.tar.xz/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2022/1/28 上午12:08
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at epe.a(SourceFile:423)
	at epe.a(SourceFile:407)
	at dxo.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:199)
Caused by: yk: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at yk.a(SourceFile:48)
	at epw.<init>(SourceFile:200)
	at epe.a(SourceFile:419)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at dry.b(SourceFile:72)
	at dry.a(SourceFile:54)
	at epw.a(SourceFile:241)
	at epw.<init>(SourceFile:182)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at epe.a(SourceFile:423)
	at epe.a(SourceFile:407)
	at dxo.<init>(SourceFile:617)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:199)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1792869416 bytes (1709 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 0 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd0a Stepping r0x1p0
	Microarchitecture: unknown
	Frequency (
GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 6115.86
	Virtual memory used (MB): 6787.95
	Swap memory total (MB): 2304.00
	Swap memory used (MB): 1165.54
	JVM Flags: 2 total; -Xms2048M -Xmx2048M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 0 (aarch64)
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2022-01-28_00.08.03-client.txt


 This is my latest log

**Comment by ajit56** [comment] 2022-01-28 04:54
You are using Zink renderer

**Comment by FloatAway** [comment] 2022-01-28 06:25
> You are using Zink renderer

Which one I use, it still crash

**Comment by SprainedSpark89** [comment] 2022-01-28 20:47
i find it weird that
Virtual memory max (MB): 6115.86
Virtual memory used (MB): 6787.95
max is 6115.86 but it is using 6787.95 using more memory than max

**Comment by 51nya51** [comment] 2022-01-30 16:54
> i find it weird that Virtual memory max (MB): 6115.86 Virtual memory used (MB): 6787.95 max is 6115.86 but it is using 6787.95 using more memory than max

How to fix it?

**Comment by 51nya51** [comment] 2022-01-30 17:41
> 

i found a way to fix it

**Comment by 51nya51** [comment] 2022-01-30 17:42
https://youtu.be/QXSlOybtdSM

**Comment by SprainedSpark89** [comment] 2022-01-31 16:35
what java version are you using

**Comment by SprainedSpark89** [comment] 2022-01-31 16:37
and did you equip the shader by pojavlauncher?

**Comment by SprainedSpark89** [comment] 2022-01-31 16:40
is your device 32 or 64 bit

**Comment by SprainedSpark89** [comment] 2022-01-31 16:45
i can't understand spanish but don't download from the minecraft links to download minecraft

**Comment by SprainedSpark89** [comment] 2022-01-31 16:52
and i would get optifine and watch some tutorial how to install fabric on forge and put the optifine jar in the mods folder try doing that with fabric and install sodium on fabric

**Comment by SprainedSpark89** [comment] 2022-01-31 16:54
i would try but i barely can run 1.16.5 so i also can't load 1.16.5 optifine but i can load into 1.16.5

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:27
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:27 UTC
Labels: bug
