### ISSUE TITLE
I can't connect my mouse

### ISSUE THREAD

**Issue by Adamevapetr** [PojavLauncherTeam/PojavLauncher#5677] opened 2024-06-25 15:19 UTC
### Describe the bug

when i connected my bluetooth mouse to the game it won't connect please solve the problem app version foxglove-20240621-332de88-v3_openjdk

### The log file and images/videos

No

### Steps To Reproduce

```markdown
No error in this
```

### Expected Behavior

I dont know

### Platform

```markdown
- Device model: Motorola g200 5g
- CPU architecture: snapdragon 888+
- Android version:11
- PojavLauncher version:foxglove-20240621-332de88-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-06-25 15:51
duplicate of #5648

**Closed as not planned by GaucovyAero** 2024-06-25 15:51 UTC
Labels: bug
