### ISSUE TITLE
[BUG] <Short description> Otg mouse or a Bluetooth mouse doesn't work. Everytime i open the game the virtual mouse appears and my mouse doesn't work

### ISSUE THREAD

**Issue by Coolboy42-89** [PojavLauncherTeam/PojavLauncher#5707] opened 2024-06-29 12:31 UTC
### Describe the bug

Otg mouse or a Bluetooth mouse doesn't work. 

### The log file and images/videos

![Uploading IMG_20240624_145306_739_transcpr.jpg…]()

### Steps To Reproduce

```markdown
1. Open pojav
2. Start game with otg mouse
3. Observe. And FIX THE BUG
```

### Expected Behavior

Otg mouse properly works

### Platform

```markdown
- Device model: infinix hot 9
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: latest foxglove
```

### Anything else?

Plz fix bug

**Comment by Kal19801** [comment] 2024-06-29 18:48
Duplicate of #5648

**Closed as not planned** 2024-06-29 19:09 UTC
Labels: bug

**Comment by BLSK666** [comment] 2024-07-03 00:53
me pasa exactamente lo mismo, por favor una solucion.
