### ISSUE TITLE
[BUG] Minecraft 1.6.4 Forge Not Working On PojavLauncher

### ISSUE THREAD

**Issue by tencentgamer2345** [PojavLauncherTeam/PojavLauncher#2029] opened 2021-09-14 04:53 UTC
### Describe the bug

When I Try to Run Minecraft Forge 1.6.4 I Found It Writes Java Exit Code O And It Doesn't Work

### The log file and images/videos

![Screenshot_2021-09-14-11-42-53-71](https://user-images.githubusercontent.com/90538355/133196577-6e03f2cd-d327-41a9-8737-b0655e6582fe.jpg)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7158953/latestlog.txt)

### Steps To Reproduce

```markdown
1.Mulai PojavLauncher
```

### Expected Behavior

I Hope It Will Work

### Platform

```markdown
- Device model:Realme 5
- CPU architecture:aarch64
- Android version:9
- PojavLauncher version:3.3.1.1_rel_20210206
```

**Comment by artdeell** [comment] 2021-09-14 05:44
You are on a very outdated launcher version

**Comment by tencentgamer2345** [comment] 2021-09-14 11:48
ok but will PojavLauncher Latest Version Will Work

**Comment by Mathias-Boulay** [comment] 2021-09-14 19:22
old launcher version, duplicate of #1733

**Closed as completed by Mathias-Boulay** 2021-09-14 19:22 UTC
Labels: bug
