### ISSUE TITLE
[BUG]1.12.2 forge crash when joining world

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2843] opened 2022-03-04 03:54 UTC
### Describe the bug

When joining world in single player
Its FC

### The log file and images/videos

![Screenshot_2022-03-04-11-08-03-80](https://user-images.githubusercontent.com/96860972/156696176-ef50cd38-014b-4fee-8c40-21a9b76d9c73.jpg)

### Steps To Reproduce

```markdown
Start pojav launcher
Play 1.12.2 forge
Joining world
CRASHED
```

### Expected Behavior

Any solution?

### Platform

```markdown
- Device model: oppo a12 3/32G
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: latest build
```

### Anything else?

I really want to play no cubes w/ shader!

**Comment by khanhduytran0** [comment] 2022-03-04 03:56
Duplicate of #2842
You must login with an online account in order to play with Forge/Fabric.

**Closed as completed by khanhduytran0** 2022-03-04 03:56 UTC
Labels: bug, duplicate
