### ISSUE TITLE
[BUG] Error on trying to install 1.8.9 forge 

### ISSUE THREAD

**Issue by stacode123** [PojavLauncherTeam/PojavLauncher#1098] opened 2021-03-22 19:36 UTC
<details> <summary>

### Describe the bug
I try to install forge 1.8.9 and it gives an error measage and exits to the main screen

**Add a log file if you want to see your bug fixed !**

Logs:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6187709/latestlog.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher

2.click on options/launch a mod instaler

3.i pick the recommended forge 1.8.9.jar installer

### Expected behavior:
To have forge installed

### Screenshots or videos:
![Screenshot_20210322-202028.jpg](https://user-images.githubusercontent.com/49679054/112047794-fdb25e80-8b4d-11eb-942b-5a8157b42ccb.jpg)

**Platform:**
 - Device Model [Huawei p10 (lite maybe) ]
-  - CPU architecture [don't know] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [ Google play store]

<details> <summary><b>Additional context</b></summary>

**Comment by khanhduytran0** [comment] 2021-03-22 22:03
You can send log on where you’ve sent image.

**Comment by stacode123** [comment] 2021-03-23 07:36
Logs added!

**Comment by khanhduytran0** [comment] 2021-03-23 07:40
Duplicate #1073: you used universal instead of installer

**Comment by khanhduytran0** [comment] 2021-04-29 08:23
@stacode123

**Comment by khanhduytran0** [comment] 2021-04-29 08:23
Duplicate of #1073

**Closed as completed** 2021-04-29 08:23 UTC
Labels: bug, duplicate
