### ISSUE TITLE
stuck in a infinite loading screen

### ISSUE THREAD

**Issue by goofballben** [PojavLauncherTeam/PojavLauncher#2792] opened 2022-02-25 02:47 UTC
### Describe the bug

when i click play i get stuck at a screen with 3 alternating dots.

### The log file and images/videos

three dots

### Steps To Reproduce

```markdown
press play
```

### Expected Behavior

i expect that i can play

### Platform

```markdown
oculus quest 2
```

**Comment by Gamerduh101** [comment] 2022-02-25 03:39
Hello! i had happen to have the same issue with my quest, assuming that's what you use. i figured out that the issue was caused by a mod that didnt want to work right (sodium), so if you happen to have a mod that seems like it wouldnt work there, i suggest removing it. 
heres a few that have been found to not currently work:
[here!](https://github.com/PojavLauncherTeam/PojavLauncher/issues/1948 )

**Comment by khanhduytran0** [comment] 2022-02-26 22:15
Duplicate of #2778

**Closed as completed by khanhduytran0** 2022-02-26 22:15 UTC
Labels: bug
