### ISSUE TITLE
[BUG] (OTG mouse) Higher polling rate = lower sensitivity"

### ISSUE THREAD

**Issue by toogitt** [PojavLauncherTeam/PojavLauncher#4763] opened 2023-10-22 21:46 UTC
### Describe the bug

I connected my mouse and keyboard to my phone to play and when i get into pojav the sensitivity is super low in game even when I set it to hyperspeed. I set the dpi on my mouse super high to temporarily fix the problem but it causes lag and jerky movement.

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. connect mouse
3. move camera
4. adjust sensitivity
```

### Expected Behavior

Expected: Normal sensitivity

### Platform

```markdown
- Device model: galaxy zflip 5
- CPU architecture: idk
- Android version: 13
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment] 2023-10-23 07:19
high dpi doesnt cause lag, but the issue is caused by you having a samsung phone (see #4762), and the slowness is a general issue caused by you having high polling rate set on the mouse

**Comment by toogitt** [comment] 2023-10-23 20:18
Thank you so much

**Comment by GaucovyAero** [comment] 2023-10-23 21:31
but it should get fixed eventually if its even possible to fix (ive seen the osu!lazer android client also has some mouse slowdown so idk)

**Comment by GaucovyAero** [comment] 2024-09-15 22:18
closing in favor of #5647

**Closed as not planned by GaucovyAero** 2024-09-15 22:18 UTC
Labels: bug, known issue, needs fixing
