### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by KingMXK** [PojavLauncherTeam/PojavLauncher#2667] opened 2022-02-03 12:17 UTC
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

### The log file and images/videos

![Screenshot_2022-02-03-14-14-58](https://user-images.githubusercontent.com/98954655/152341203-acd5fe6d-5f28-428e-b7bd-04b13de9ef76.png)

### Steps To Reproduce

```markdown
Changed the allocated ram
```

### Expected Behavior

I expect the game to launch 1.7.10

### Platform

```markdown
- Device model: Samsung galaxy J3 2016
- CPU architecture: Quad-core (4×1.5 GHz) ARM Cortex-A7 quad-core (4×1.3 GHz) ARM Cortex-A7 quad-core (4×1.2 GHz) ARM Cortex-A7
- Android version: 5.1.1
- PojavLauncher version:  [Latest Release || version 3.3.1.1_rel_20210206 ]
```

### Anything else?

![Screenshot_2022-02-03-14-14-58](https://user-images.githubusercontent.com/98954655/152340915-6f6d8647-a362-498c-a39b-68848b8d4861.png)

**Comment by SprainedSpark89** [comment] 2022-02-03 18:43
turn down memory

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:32
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:32 UTC
Labels: bug
