### ISSUE TITLE
[BUG] Unable to load 1.19.2 on the latest version of the launcher

### ISSUE THREAD

**Issue by Imbored702** [PojavLauncherTeam/PojavLauncher#5697] opened 2024-06-27 19:04 UTC
### Describe the bug

Recently, my previous worlds and profile were completely fine before the latest version that was released a few days ago. Now, as soon as I updated to the latest version, the game will refuse to load up 1.19.2 again. I tried changing the render, deleting certain mods on my forge profile, and deleting the launcher altogether, 1.19.2 would not work at all using Java 17. I tried using Java 17 on the log provided for Chromebooks, (JRE 86 x 64) but I end up with the infamous missing textures glitch, no text or textures would appear in game. The game crashed on all modded profiles (Forge,Fabric and Quilt), as well as vanilla and optifine profiles. I even tried running different versions that use Java 17, and they still crashed. This all happened immediately after the latest update, everything was completely normal before.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16019727/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the launcher
2. Select versions 1.18-1.19.4 using JRE 17
3. start the game
```

### Expected Behavior

The game will load onto the Mojang studios logo screen but crashes immediately upon startup

### Platform

```markdown
- Device model: Google Grunt 
- CPU architecture: x86-64 Chromebook
- Android version: 11
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-06-28 14:01
duplicate of #5674

**Closed as not planned by GaucovyAero** 2024-06-28 14:01 UTC
Labels: bug
