### ISSUE TITLE
Unable to drag mouse after June 21 update

### ISSUE THREAD

**Issue by MattTheCuber** [PojavLauncherTeam/PojavLauncher#5655] opened 2024-06-23 01:33 UTC
### Describe the bug

In touchscreen mode (mouse off) before the update I was able to drag my finger to hover over a spot on the screen. This allowed me to hover over an item in my inventory to view the lore. After the update yesterday, when I drag my finger it picks up the item where finger started dragging from so that I am unable to see the lore. If you need more explanation, let me know.

I might revert to the previous version until this is fixed as being able easily to see an item's lore is pretty crucial for me.

### The log file and images/videos

N/A

### Steps To Reproduce

```markdown
1. Start Pojav, and enter a world.
2. Turn off mouse mode
3. Open you inventory
4. Drag your finger so that the "I visible cursor" is hovering over an item
5. Notice that the item is picked up so that you are not viewing the lore as if you were hovering over the item.
```

### Expected Behavior

I would expect dragging my finger would not perform any clicks. Just like it did before yesterday.

### Platform

```markdown
- Device model: Google Pixel 7
- CPU architecture: N/A
- Android version: 14
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-06-24 08:02
duplicate of #5648

**Closed as not planned by GaucovyAero** 2024-06-24 08:02 UTC
Labels: bug
