### ISSUE TITLE
Can't run Angelica

### ISSUE THREAD

**Issue by EvenWen1215** [PojavLauncherTeam/PojavLauncher#5428] opened 2024-05-04 09:40 UTC
### Describe the bug

when i use Angelica +unimixins gtnhlib it will crash
But there are no problems when running gtnhlib + unimixins

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/15209245/latest.log)

### Steps To Reproduce

```markdown
run pojavlauncher and it Flashback
but when i use zink It will run but it is inefficient
```

### Expected Behavior

i hope it can run

### Platform

```markdown
- Device model: Redmi k60 pro
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment] 2024-05-04 10:38
duplicate of #5416

**Closed as not planned by GaucovyAero** 2024-05-04 10:38 UTC
Labels: bug
