### ISSUE TITLE
The ability to turn off the controller mapping.

### ISSUE THREAD

**Issue by AdroitJackson** [PojavLauncherTeam/PojavLauncher#5505] opened 2024-05-28 15:30 UTC
### Describe the request.

When connecting a controller it automatically brings up a button mapping screen pre mapping the controller but fabric mods like example controllable have the chance of picking up the controller allowing you to use it So I personally believe that the ability to turn on and off the controller mapping and using at will.

**Comment by GaucovyAero** [comment] 2024-05-29 10:07
duplicate of #4486

**Closed as not planned by GaucovyAero** 2024-05-29 10:07 UTC
Labels: enhancement

**Comment by AdroitJackson** [comment] 2024-05-29 14:55
> duplicate of #4486

Is there A way to disable it already then? I just read over that

**Comment by GaucovyAero** [comment] 2024-05-29 15:41
nope, hence why that issue is not closed yet
