### ISSUE TITLE
bugs 1.21

### ISSUE THREAD

**Issue by Zack140-wq** [PojavLauncherTeam/PojavLauncher#6011] opened 2024-08-31 22:09 UTC
### Describe the bug

eu entro e o jogo mostra intens invisiveis na 1.21 somente 

### The log file and images/videos

My pojavlauncher is bugged, I've been trying to enter 1.21 for a few days now. When I enter, the invisible items simply appear. I think it's the renderer, but my cell phone is a Redmi 9a. I simply change the renderer, put the normal one, the hotbar doesn't appear, but the same way. I have the problem, I hope they resolve it soon and fix both the 1.21 bug and the hotbar bug disappear from version 1.17 because the renderer that already comes with the launcher is light and I want to play my minecraft less laggy and what do you tell me? Understand, please fix it as soon as possible.

### Steps To Reproduce

```markdown
I open my pojavlauncher, I go into my server, I spend a few second playing Dunada, my fps drops to 0 and crashes for no reason at all
```

### Expected Behavior

I hope that 1.21 will be debugged and that the game will remove the crashes and improve the game even more by making clients work and leaving the option to enlarge the mouse in the game when you click on the gear and allowing me to put my minecraft bedrock accounts on pojavlauncher

### Platform

```markdown
- Device model: redmi 9a
- CPU architecture: 
I don't know
- Android version: 10
- PojavLauncher version: 
the last
```

### Anything else?

My pojavlauncher is bugged, I've been trying to enter 1.21 for a few days now. When I enter, the invisible items simply appear. I think it's the renderer, but my cell phone is a Redmi 9a. I simply change the renderer, put the normal one, the hotbar doesn't appear, but the same way. I have the problem, I hope they resolve it soon and fix both the 1.21 bug and the hotbar bug disappear from version 1.17 because the renderer that already comes with the launcher is light and I want to play my minecraft less laggy and what do you tell me? Understand, please fix it as soon as possible.

**Comment by GaucovyAero** [comment] 2024-09-02 17:36
pojavlauncher version is not filled out, make sure to actually check the version, like `foxglove-x-x-x-v3_openjdk`

**Comment by GaucovyAero** [comment] 2024-09-04 18:45
closing, cant reproduce the issue on my PowerVR GE8320 64-bit Galaxy A12 (running stock Samsung firmware)

**Closed as not planned by GaucovyAero** 2024-09-04 18:45 UTC
Labels: bug, fill the template, device-specific
