### ISSUE TITLE
1.17 - 1.18

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#2590] opened 2022-01-20 08:17 UTC
### Describe the bug

1.17 - 1.18 Virglrender working but using shader not working

### The log file and images/videos

Using shader become green and white on 1.17 using virgl render

### Steps To Reproduce

```markdown
1
```

### Expected Behavior

2

### Platform

```markdown
- Device model: bison umidigi
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest on github
```

### Anything else?

Fix plss

**Comment by Errorbot1122** [comment] 2022-01-20 23:10
Please fill in the **`Steps To Reproduce`** and **`Expected Behavior`** sections. 

Also, move your:

> Using shader become green and white on 1.17 using virgl render

to **`Describe the bug`** Section and add your `latestlog.txt` file to it (or just copy and paste the `crash log` and add it in between a code section)

**Comment by kedrick021** [comment] 2022-01-23 04:34
Only for 1.18.1 working on shader

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:18
The issue is fixed on the release candidate build.

**Closed by Mathias-Boulay** 2022-05-23 22:18 UTC
Labels: bug
