### ISSUE TITLE
[F-Req] add an "reload version list" button

### ISSUE THREAD

**Issue by AhmedGhaithX** [PojavLauncherTeam/PojavLauncher#6059] opened 2024-09-11 17:04 UTC
### Is this request related to a bug?

Having to wait for the auto version list loading

### Describe the request.

Instead of waiting for the app to automatically reload the version list you should add a reload version list button.

**Comment by GaucovyAero** [comment] 2024-09-11 20:00
duplicate of #5576

**Closed as not planned by GaucovyAero** 2024-09-11 20:00 UTC
Labels: enhancement
