### ISSUE TITLE
BRING Back The Auto Ram setting

### ISSUE THREAD

**Issue by JohnPrinceDugan** [PojavLauncherTeam/PojavLauncher#2078] opened 2021-09-28 13:26 UTC
### Is this request related to a bug?

The Auto ram setting automatically set the ram on your phone instead of manualy choosing the maximum ram

### Describe the request.

THE auto ram setting

**Comment by khanhduytran0** [comment] 2021-09-28 13:30
guess what? Then you will put the app to background, open some heavy apps and ask why pojav is closing in background

**Comment by khanhduytran0** [comment] 2021-09-28 13:43
Duplicate of #1702 (touch the search bar if you want to see more duplicates)

**Comment by khanhduytran0** [comment] 2021-09-28 13:44
Duplicate of #1702

**Closed as completed by khanhduytran0** 2021-09-28 13:44 UTC
Labels: duplicate, enhancement
