### ISSUE TITLE
[BUG] Unable to resolve hostname

### ISSUE THREAD

**Issue by NoxiWave** [PojavLauncherTeam/PojavLauncher#5728] opened 2024-07-02 15:00 UTC
### Describe the bug

I enter server on Pojav Launcher and it says "Unable to resolve hostname". It's Launcher problem because it works for my PC well. I know it's a duplicate but first issue got opened almost 3 years ago, and it still didnt got fixed.

### The log file and images/videos

Cannot get.

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Select version
3. Start game
4. Go in Multiplayer
5. Enter specific IP server
6. See the error
```

### Expected Behavior

I expect server connect normally.

### Platform

```markdown
- Device model: Xiaomi Redmi Note 12S 8/128gb
- CPU architecture: Not pretty sure. 64-bit CPU.
- Android version: 14
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

Don't ignore this issue.

**Comment by GaucovyAero** [comment] 2024-07-03 15:49
> Enter specific IP server

means we have literally no way of testing this since servers having this issue are mostly private for whatever reason, means we dont get the ips

**Comment by GaucovyAero** [comment] 2024-07-03 15:50
duplicate of #5243 and #4479

**Comment by NoxiWave** [comment] 2024-07-04 10:18
> duplicate of #5243 and #4479

Did you see what I wrote?

**Closed as completed** 2024-09-11 16:24 UTC
Labels: bug, duplicate, known issue, needs fixing
