### ISSUE TITLE
[BUG]1.12.2 forge crash w/ virgl 

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2842] opened 2022-03-04 03:14 UTC
### Describe the bug

When joining single player world its crashing!

### The log file and images/videos

![Screenshot_2022-03-04-11-08-03-80](https://user-images.githubusercontent.com/96860972/156692073-e6153988-1f12-4c84-ab0d-cc048281faae.jpg)
``

### Steps To Reproduce

```markdown
Start pojav launcher
Play 1.12.2 forge
Joining world
FORCE CLOSE
```

### Expected Behavior

Any solution for this

### Platform

```markdown
- Device model: oppo a12 3/32G
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: Latest build
```

### Anything else?

Pls solution i want to play no cubes w/ shader

**Comment by khanhduytran0** [comment] 2022-03-04 03:17
Duplicate of #2679

**Closed as completed by khanhduytran0** 2022-03-04 03:17 UTC
Labels: bug, duplicate
