### ISSUE TITLE
[BUG] Issue with toggle buttons

### ISSUE THREAD

**Issue by Zelioz273** [PojavLauncherTeam/PojavLauncher#963] opened 2021-02-25 18:30 UTC
### Describe the bug
This could also be a feature request, but i felt like it should be a bug as in something that should be looked into.
Cannot activate/deactivate toggle buttons while holding down screen(for example, to look around).

**Add a log file if you want to see your bug fixed !**
If it's needed in this case, i can send it but i don't think it's needed here

### To Reproduce:
1. Start PojavLauncher
2. Go into world
3. Hold the screen with any finger
4. Try to press(activate/deactivate) a button that has the toggle feature enabled
5. Button does not respond(nor does it turn blue)

### Expected behavior:
I expected the button to toggle and untoggle regardless if i'm holding down the screen

**Platform:**
 - Device Model: Samsung note9
 - CPU architecture: aarch64
 - Android Version: 10
 - PojavLauncher Version: Latest build as of now

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Of the buttons i mentioned that toggle option enabled, one of them is keymapped to a mod, and the other is f3.
</pre>
</details>

**Comment by Mathias-Boulay** [comment] 2021-06-08 13:55
Hey @Zelioz273 , the issue is finally being taken into account and a fix for this is on the way.
Don't ask for an ETA though, else I would have provided it 👀

**Comment by Zelioz273** [comment] 2021-06-08 17:14
Oh nice then. Should i close this since it's already being fixed?

**Comment by Mathias-Boulay** [comment] 2021-06-09 11:30
I may as well close it, since I'm trying to de-clutter to see current issues.

**Closed as completed by Mathias-Boulay** 2021-06-09 11:30 UTC
Labels: bug
