### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Chesper31** [PojavLauncherTeam/PojavLauncher#5945] opened 2024-08-16 13:36 UTC
### Describe the bug

My cursour is very slippery and unusable only in pojav launcher

https://github.com/user-attachments/assets/9494c8c1-553e-4b6e-8d75-214888afe84d

Bdw i use an otg hub

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16637648/latestlog.txt)

### Steps To Reproduce

```markdown
1.lqunch Minecraft
2.try to play
3.andjust the pointer sens
5.still sliperry
```

### Expected Behavior

I expected my pinter to worck like on every other app,eith my sensivty and thinkgs,not to be verry slippery and unuseabele

### Platform

```markdown
- Device model: pocox3pro
- CPU architecture: arm65 i think
- Android version: 13
- PojavLauncher version: leatest
```

### Anything else?

Any fixes?

**Comment by GaucovyAero** [comment] 2024-08-16 16:06
duplicate of #5647, try lowering your polling rate

**Closed as not planned by GaucovyAero** 2024-08-16 16:06 UTC
Labels: bug
