### ISSUE TITLE
[BUG] i can click half layers when use otg mouse

### ISSUE THREAD

**Issue by BUCIOJEK** [PojavLauncherTeam/PojavLauncher#5257] opened 2024-03-25 13:24 UTC
### Describe the bug

After i upgrade my android to 14 i can click half layers in game like, i can click the right layer but Its cant on right layer: [✔️l✖️] like this
I can click the button controller on all layers but not in game. I cant play Minecraft when my cursor on the right layer i can click any think on Minecraft when my cursor on right. So please fix this bug i want to play Minecraft for my YouTube 

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/89052261/93ed0d45-28b9-431e-9ffb-134b4227268c

### Steps To Reproduce

```markdown
I just start the Minecraft when its in i cant click half layers
```

### Expected Behavior

The keyboard to its don't work to i can click esc and other 

### Platform

```markdown
- Device model: Realme c55
- CPU architecture: holio g88
- Android version: 14
- PojavLauncher version: v3_openjdk
```

### Anything else?

Please fix this bug

**Comment by GaucovyAero** [comment] 2024-03-25 15:31
duplicate of #5000, try reinstalling pojav and see if it maybe fixes the issue and report back

**Closed as not planned by GaucovyAero** 2024-03-25 15:31 UTC
Labels: bug

**Comment by BUCIOJEK** [comment] 2024-03-26 03:33
> duplicate of #5000, try reinstalling pojav and see if it maybe fixes the issue and report back

I do it but ITS dosnt work Its good when they add slide mouse to this game mybe that can fix if they add thats fiture
