### ISSUE TITLE
[BUG] Microsoft login fails

### ISSUE THREAD

**Issue by Crystal-l-l** [PojavLauncherTeam/PojavLauncher#2592] opened 2022-01-20 13:49 UTC
### Describe the bug

When logging in, the microsoft login gets to 33 percent then displays an error message. The app does not close, and the message displays "Copy", "Show more", and "Ok" buttons. Pressing copy copies the error. Show more shows the full error. Ok closes the error window, leaving the user back at the login screen (where you can enter Mojang account window, press the microsoft login button, etc.)

### The log file and images/videos

javax.net.ssl.SSLPeerUnverifiedException: Hostname user.auth.xboxlive.com not verified:
    certificate: sha1/UWZu+TBdukZhT5sR6ssDxTcykHs=
    DN: CN=*.att.llabs.io
    subjectAltNames: [*.att.llabs.io, *.int.att.llabs.io]
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:115)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

### Steps To Reproduce

```markdown
1. Start the launcher
2. Use Microsoft login
3. Login using Microsoft login
4. When loading it displays the error message
```

### Expected Behavior

It was expected to login without error, as it has done in the past.

### Platform

```markdown
- Device model: SM-N970U
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: (according to google play) crocus-v3_openjdk 
I think this would be the latest release, but I am not entirely sure.
```

### Anything else?

-There is an alternate pojav launcher in secure folder with a different Microsoft account that works just fine, gets past 33 percent and is able to play.
-Both were installed from the Google Play store, in case any alternative download links exist.

**Comment by khanhduytran0** [comment] 2022-01-20 13:53
> Hostname user.auth.xboxlive.com not verified:
certificate: sha1/UWZu+TBdukZhT5sR6ssDxTcykHs=
DN: CN=.att.llabs.io
subjectAltNames: [.att.llabs.io, *.int.att.llabs.io]

This can be either the clock time in your device is wrongly set or certificate was uninstalled somehow.

**Comment by 1493028** [comment] 2022-01-26 02:52
Сначала у вас должна быть учетная запись Mojang, затем вы переходите на учетную запись Microsoft, а затем пытаетесь войти в свою учетную запись Microsoft.

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:20
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:20 UTC
Labels: bug
