### ISSUE TITLE
[F-Req] Add NeoForge Profiles Update

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5212] opened 2024-03-10 04:08 UTC
### Is this request related to a bug?

![Screenshot_20240310_110748](https://github.com/PojavLauncherTeam/PojavLauncher/assets/154730274/fc058be4-5906-4b51-84e6-3de44969a142)

### Describe the request.

Please Add NeoForge Profiles In Pojav Launcher

### Anything else?

Please Fix Bug Forge 1.20.4

**Comment by ind33deda** [comment] 2024-03-30 05:47
#5203 likely

**Comment by GaucovyAero** [comment] 2024-09-15 22:34
duplicate of #4523

**Closed by GaucovyAero** 2024-09-15 22:34 UTC
Labels: enhancement, worth considering
