### ISSUE TITLE
[BUG] <1.7.2 or bellow bugs>

### ISSUE THREAD

**Issue by Shromeyy** [PojavLauncherTeam/PojavLauncher#2518] opened 2022-01-07 12:07 UTC
### Describe the bug

1.0 to 1.1 there is sound but the gameplay is not in full screen the screen is on the bottom left (you can see the image bellow) 1.2.1 to 1.2.4 the game crash 1.2.5 to 1.5.2 there is sound but the gameplay screen is at the bottom left 1.6.1 to 1.7.2 the game is in full screen but no sound.

### The log file and images/videos

![Screenshot_20220107-142342_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/94804069/148538548-940241c7-bb84-41a0-8d98-12a38000fe16.jpg)
![Screenshot_20220107-143220_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/94804069/148538566-9c17b3b8-0624-4726-bed3-e92d8fad7587.jpg)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
```

### Expected Behavior

:)

### Platform

```markdown
- Device model: Galaxy A31
- CPU architecture: aarch64
- Android version: Android 11
- PojavLauncher version: crocus-309-10e4187a7-v3_openjdk
```

**Comment by NotAHero04** [comment] 2022-01-07 12:16
These are known bugs with older versions of Minecraft.
- I can reproduce the 1.2.1-1.2.4 crash, and the 1.6- sound bug (this is due to the download server)
- 1.6+ sounds should work normally, please check it again.
- You can bring the game to full screen by pressing F11.

**Comment by Mathias-Boulay** [comment] 2022-05-23 21:52
Fixed in the release candidate build

**Closed as completed by Mathias-Boulay** 2022-05-23 21:52 UTC
Labels: bug
