### ISSUE TITLE
Game refuses to load into any world with (performance or graphical) mods installed.

### ISSUE THREAD

**Issue by zwtgithbu** [PojavLauncherTeam/PojavLauncher#6397] opened 2024-12-20 00:30 UTC
### Describe the bug

when I try to play either multiplayer or local worlds with OptiFine, sodium or any mod for that matter, my game crashes with the error "Application/ Game aborted by fatal signal 6"

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18204293/latestlog.txt)

I read some of the logs, something to do with wrong version of JNA native library installed maybe?

![Screenshot_20241219_210757](https://github.com/user-attachments/assets/be414a54-ccc0-444b-bde5-83734c236ed6)
or something to do with this: (libGLES_mali.so+0x74f1a0)

![Screenshot_20241219_210855](https://github.com/user-attachments/assets/554a926b-64e4-4a52-9e20-6ca881828ce2)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Add a OptiFine /Fabric + Sodium profile within the selector
3. Start Minecraft with a local account 
4. Load into any world
5. Crashes a few seconds after the loading screen hits 100%
```

### Expected Behavior

Render the world normally and play as usually.

### Platform

```markdown
- Device model: A34 5G (SM-A346M/DSN)
- CPU architecture: arm64 MediaTek Dimensity 1080 (MT6877V) ARM Cortex-A78
- Android version: 14, OneUI: 6.1
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

Game runs completely fine when no mods are running, even just running fabric with nothing on.

**Comment by 1fbw2** [comment] 2024-12-20 22:23
same here, any fix?

**Comment by CamoWolf1222** [comment] 2024-12-23 16:56
Duplicate of #6325, there seems to be a fix in #6377

**Comment by zwtgithbu** [comment] 2024-12-23 18:45
game works and runs, but still crashes if there are any performance/visually tweaking mods, for example I can run 20+ mods in fabric, but if I put a single performance mod (sodium, iris, lithium, or only run OptiFine), it still gives error 6

**Comment by CamoWolf1222** [comment] 2024-12-23 18:46
I changed my renderer to zink and that i think that fixed it

**Comment by zwtgithbu** [comment] 2024-12-23 22:17
now my game crashes from the get go, just starting up Minecraft gives me an error -1 after I changed the renderer to Zink 

I think my GPU in my phone may be incompatible? but I have no idea if that could be the case

**Comment by CamoWolf1222** [comment] 2024-12-23 23:36
> I think my GPU in my phone may be incompatible?

I highly doubt that (although I could be wrong). Idk what else you could do. I was just flipping around some settings that may have had something to do with my issue, and then it worked. Can't help you any more beyond this point.

**Comment by GaucovyAero** [comment] 2024-12-27 15:47
reset your video settings

**Closed as completed by GaucovyAero** 2024-12-27 15:47 UTC
Labels: bug
