### ISSUE TITLE
[BUG] mouse doesnt work

### ISSUE THREAD

**Issue by Minecrafterz104** [PojavLauncherTeam/PojavLauncher#5670] opened 2024-06-24 10:58 UTC
### Describe the bug

the mouse is not moveable in-game and menu. but moveable in the launcher

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/142328769/8bd166a2-a845-4fa9-b19c-c1b5e6e85f41

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. move your bluetooth or wired mouse
```

### Expected Behavior

the android mouse cursor immediately dissappear and the pojav cursor appears in the middle

### Platform

```markdown
- Device model: Vivo V15 Pro 6/128G
- CPU architecture: Octa-core (2x2.0 GHz Kryo 460 Gold & 6x1.7 GHz Kryo 460 Silver)
- Android version: 11
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk (latest)
```

**Comment by GaucovyAero** [comment] 2024-06-24 11:16
duplicate of #5648

**Closed as not planned by GaucovyAero** 2024-06-24 11:16 UTC
Labels: bug
