### ISSUE TITLE
[BUG] In-game bugs when using OTG mouse

### ISSUE THREAD

**Issue by andteklin** [PojavLauncherTeam/PojavLauncher#2246] opened 2021-11-15 20:47 UTC
### Describe the bug

When using a mouse and keyboard connected to the Samsung Galaxy S9 using a USB-C hub, there are two situations in which occur with mouse interactions:

1. When "Touchscreen Mode" is set to **ON**, all doors, levers, chests, etc. open properly without issue. The only problem when using mouse with this setting on is that you cannot use in-game shortcuts like Shift + Click to instantaneously place items from inventory to chest or just simply left-clicking an item in your inventory to move it. You have to drag items and treat it like you're playing on a phone. 
2. When "Touchscreen Mode" is set to **OFF**, all doors, levers, chests, etc. **do not open properly**. For example, when you try to right click on the door, it will double click the door in an instant and it will return to the original position from before you clicked. Same goes for lever, and even water buckets will not collect properly, which is a major concern. 

All these have been tested in the README.md Actions version of v3_openjdk using 1.17.1 Optifine HD U G9 and Java 8. It has also been tested using vanilla 1.17.1 using JRE17 for arm64. Turning on/off _disable gestures_ in the PojavLuncher settings does not seem to make a difference, it actually might cause the mouse to stop working at times too. 

### Steps To Reproduce

```markdown
1. Start PojavLauncher using 1.17.1 using default.json controls and a connected mouse and keyboard
2. Open Minecraft settings --> Options --> Controls --> Mouse Settings --> Touchscreen Mode: OFF
3. Enter a Minecraft world, place a door, test picking up water with bucket, and lever, you will see the bug
4. Turn Touchscreen Mode: ON and test it. Now it works. But try moving stuff into a chest. It will not register commonly known shortcuts like Shift + Click to instantly move items into a chest.
```

### Expected Behavior

When using a mouse and keyboard, it is expected that doors open properly, levers work, and water picks up properly when using this version of Minecraft on PojavLauncher on an Android. 

### Platform

```markdown
- Device model: Samsung Galaxy S9/64G
- CPU architecture: Octa-Core, 2 processors: 2.7GHz Quad-Core Mongoose M3 1.8GHz Quad-Core ARM Cortex-A55
- Android version: 10
- PojavLauncher version: crocus-103-21f6b166a-v3_openjdk
```

### Anything else?

_Originally posted by @smartmonkey3042 in https://github.com/PojavLauncherTeam/PojavLauncher/issues/2231#issuecomment-966748515_

**Comment by Mathias-Boulay** [comment] 2021-11-19 20:17
Can you contact me on discord ?
On the pojav discord, look for the control guy

**Comment by Mathias-Boulay** [comment] 2021-11-22 17:23
Touchscreen mode isn't supported with physical devices *(nor touch devices for that manner)*
As for the bugs left, they are a duplicate of much older issues

**Closed as completed by Mathias-Boulay** 2021-11-22 17:23 UTC
Labels: bug
