### ISSUE TITLE
[BUG] Unknown host on my aternos server 1.20.1

### ISSUE THREAD

**Issue by n3dd4t** [PojavLauncherTeam/PojavLauncher#6176] opened 2024-10-18 06:00 UTC
### Describe the bug

When i connect to my aternos server, it just gives me "Unknown host", and thats all, i tried changing my dns to 8.8.8.8 8.8.4.4 or 1.1.1.1 1.1.0.1 but it still gives this erroe

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17428954/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start game
2. Tap Multiplayer button
3. Add aternos server
4. Try to connect to it
```

### Expected Behavior

I expect to connect to my server without any problems

### Platform

```markdown
- Device model: Redmi Note 10S
- CPU architecture: arm64
- Android version: 13/MIUI 14.0.5.0
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-10-20 09:07
duplicate of #4479

**Closed as not planned by GaucovyAero** 2024-10-20 09:07 UTC
Labels: bug
