### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by BottomotPH29** [PojavLauncherTeam/PojavLauncher#2650] opened 2022-01-30 08:14 UTC
### Describe the bug

Application exited with code 1

### The log file and images/videos

Block screen

### Steps To Reproduce

```markdown
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 1/30/22, 8:06 AM
Description: Initializing game

java.lang.RuntimeException: could not preload blit shader
	at enb.a(SourceFile:403)
	at dvp.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:179)
Caused by: wz: Invalid shaders/core/blit_screen.json: Couldn't compile vertex program (minecraft:shaders/core/blit_screen.vsh, blit_screen) : No Shader support with current backend
	at wz.a(SourceFile:48)
	at ent.<init>(SourceFile:197)
	at enb.a(SourceFile:401)
	... 2 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/blit_screen.vsh, blit_screen) : No Shader support with current backend
	at dqa.b(SourceFile:72)
	at dqa.a(SourceFile:54)
	at ent.a(SourceFile:237)
	at ent.<init>(SourceFile:179)
	... 3 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at enb.a(SourceFile:403)
	at dvp.<init>(SourceFile:617)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:179)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 722888704 bytes (689 MiB) / 1268776960 bytes (1210 MiB) up to 1268776960 bytes (1210 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd05 Stepping r0x0p1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5934.67
	Virtual memory used (MB): 4467.92
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 1163.15
	JVM Flags: 2 total; -Xms1210M -Xmx1210M
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 1.5 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: 8x
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Galaxy A12 
- CPU architecture: Aarch64 
- Android version: 11
- PojavLauncher version: 1.17.1
```

### Anything else?

1.17.1 bug

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:31
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:31 UTC
Labels: bug
