### ISSUE TITLE
[BUG] <Short description>Application/Game aborted by fatal signal 6, check latestlog.txt for more details. pojavlauncher.

### ISSUE THREAD

**Issue by dimamamamak** [PojavLauncherTeam/PojavLauncher#6401] opened 2024-12-22 07:26 UTC
### Describe the bug

I enter the world with mod "nemezida client" and I'm crashing with an error "Application/Game aborted by fatal signal 6, check latestlog.txt for more details."

### The log file and images/videos

![Screenshot_2024-12-22-11-06-51-54_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/user-attachments/assets/d222a538-e8df-4602-9325-0a8cc19e102c)
[latestlog.txt](https://github.com/user-attachments/files/18221063/latestlog.txt)

### Steps To Reproduce

```markdown
I log into the world or server and i have crash
```

### Expected Behavior

I expect to be able to log into the world or the server. 

### Platform

```markdown
- Device model: realme 9 pro
- CPU architecture: Qualcomm® Snapdragon™™ 695 5G

Octa-core
- Android version: 14
- PojavLauncher version: past (foxglove-20241124-a5d02c1-v3_openjdk)
```

**Comment by CamoWolf1222** [comment] 2024-12-23 16:56
Duplicate of #6325, there seems to be a fix in #6377

**Comment by Its-porodx** [comment] 2024-12-27 11:56
I have the same error(

**Comment by GaucovyAero** [comment] 2024-12-27 14:46
that server is most likely just using custom shaders that gl4es cant handle

**Closed as not planned by GaucovyAero** 2024-12-27 14:46 UTC
Labels: bug
