### ISSUE TITLE
RIGHT CLICK IN MRCRYFISH GUN MOD NOT WORKING

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1596] opened 2021-06-27 08:34 UTC
Describe the bug
Am playing mrcryfish gun mod 1.16.5 when right click the gun is not crossed or zooming

Mrcryfish gun mod 1.16.5 link:
https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod

Add a log file if you want to see your bug fixed !

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6721258/latestlog.txt)

The log file called latestlog.txt is located under "Android/data/net.kdt.pojavlaunch/files", "games/PojavLauncher/" or "games/PojavLauncher/.minecraft" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

Platform:
https://www.google.com/amp/s/m.gsmarena.com/xiaomi_mi_9t-ampp-9738.php

Start PojavLauncher
... (your set of actions to reproduce the bug)
Launch forge 1.16.5
Modified the setting
Select the world
Get a gun and right click
Not working

Expected behavior:
I expected right click are working

Screenshots or videos:
https://youtu.be/1a7nmA_w97g

Device Model [e.g. Mi 8 Pro 8/128] mi 9t
CPU architecture [e.g. aarch64] aarch64
Android Version [e.g. 10] 10
PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by khanhduytran0** [comment] 2021-06-27 08:36
Duplicate of #1063

**Comment by khanhduytran0** [comment] 2021-06-27 08:37
@kedrick021 🤦 : login offline account using email?

**Closed as completed by khanhduytran0** 2021-06-27 08:36 UTC
Labels: bug, duplicate

**Comment by khanhduytran0** [comment] 2021-06-27 08:37
Bruh

**Comment by khanhduytran0** [comment] 2021-06-27 08:37
What’s the point of logging in using email if you have enabled offline mode?

**Comment by kedrick021** [comment] 2021-06-27 09:15
Close? Why the right click on mrcryfish gun mod in 1.16+ not working Do you have a solution?
