### ISSUE TITLE
[BUG] Controls making ingame keys getting stuck if I just tapped it one time.

### ISSUE THREAD

**Issue by XbxStudiosGit** [PojavLauncherTeam/PojavLauncher#5850] opened 2024-07-24 15:18 UTC
### Describe the bug

When I start up new versions of minecraft like 1.18 and above, I always get this bug from Vanilla, Forge, Fabric and much more.

This bug happens if I tapped unto a button like forwards, jumping, or any other control it gets stuck in game. Like if you press W in your keyboard on your keyboard you press it one time and the key gets stuck ingame and makes you move forward without touching the key.

I hope you address this bug because it's been annoying playing newer versions with this bug.

### The log file and images/videos

It sometimes will happen. There isn't any logs or screenshots because there isn't any logs while screenshots or video evidence is none existent because I haven't simply recorded the bug.

Note: it happens randomly, it may not happen when you logged into the world it may happen sooner.

### Steps To Reproduce

```markdown
1. Install a version of forge or fabric 1.18+ and Vanilla for 1.19+

2. Start the game.

3. Load a new world.

4. Touch the controls.
```

### Expected Behavior

The key is held if you just pressed it one time

### Platform

```markdown
- Device model: M2103K19G
- CPU architecture: Octa-core Max2.2GHz
- Android version: 11 RP1A.200720.011
- PojavLauncher version: Latest
```

**Comment by Fede2782** [comment] 2024-07-29 07:19
Same issue on Samsung Galaxy A34 5G, Android 14, on 1.21 Fabric

**Comment by GaucovyAero** [comment] 2024-07-30 09:34
we are unable to fix it for a very long time because its not consistently reproducable and devs dont have much time
duplicate of #4469

**Closed as not planned by GaucovyAero** 2024-07-30 09:34 UTC
Labels: bug
