### ISSUE TITLE
[BUG] Unable to install Forge

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#3876] opened 2023-01-26 05:53 UTC
### Describe the bug

In the latest beta version, an error was reported when Forge was installed

### The log file and images/videos

![Screenshot_20230126_134420_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/100058929/214767495-d733adca-ec0f-4c4e-b2a9-a5c551e1436f.jpg)

### Steps To Reproduce

```markdown
ni
```

### Expected Behavior

I hope this bug is fixed

### Platform

```markdown
- Device model: ART-AL00
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: Style: Ensure alpha value on TextureView
```

### Anything else?

no

**Comment by GaucovyAero** [comment] 2023-01-26 06:01
this is not a bug in pojav, forge works. 
1. Make sure you download the forge installer JAR with Firefox (not Chrome)
2. Set Java 8 (Internal) runtime as default
3. Install Forge

**Comment by GaucovyAero** [comment] 2023-01-26 06:38
closing as it has been answered and there is no other solution, forge works.
- maybe try checking your internet connection

**Closed as not planned by GaucovyAero** 2023-01-26 06:38 UTC
Labels: bug, duplicate
