### ISSUE TITLE
"sticky keys" bug with Bluetooth m&kb

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5104] opened 2024-01-28 05:41 UTC
### Describe the bug

This bug is making my key stay hold until i pressed another key.
Also, when i press "T" or "/" to open the chat, it type in another t or / in the chat box.
In the video , i show my hand cam to prove and show the mods list.
There are only 3 mods that affected the keybinds:
+ Auto Clicker (it only enable when pressing a key)
+ Modern KeyBinding (add a feature to define a keybinding's activation key with key modifiers. Like "Ctrl + G" or "Alt + S")
+ RebindMyKeys (un-bind keys and bind special things like debug screen)

Here's the video, it's 90mb so I can't drop it directly here.
https://drive.google.com/file/d/1-y5eimyPhCuaHWrYc9QU8vqqnDINt9J2/view?usp=drivesdk

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14075061/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Enter the game (1.20.4 modified)
3. Enter the server
```

### Expected Behavior

I expected my keyboard and mouse work normal 

### Platform

```markdown
- Device model: pixel 3 4/64 blueline
- CPU architecture: arm64 
- Android version: 12 lastest 
- PojavLauncher version: lastest on gg play store.version edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-01-30 19:45
please get in touch with us via pojav discord, we need your help, because you are probably the only person that can consistenly reproduce this issue
closing as this is a duplicate of #4469

**Comment by TylerHaoNhot** [comment] 2024-01-30 20:02
> please get in touch with us via pojav discord, we need your help, because you are probably the only person that can consistenly reproduce this issue closing as this is a duplicate of #4469

For sure. Here is my discord username if you ever need to DM me or smth. 
sustyler128

**Closed as not planned** 2024-06-05 20:48 UTC
Labels: bug

**Comment by rsxramin** [comment] 2024-07-13 05:11
will this not be fixed?
