### ISSUE TITLE
[BUG] <Cursor otg mouse can't move>

### ISSUE THREAD

**Issue by Fahririzqi12** [PojavLauncherTeam/PojavLauncher#5660] opened 2024-06-23 11:52 UTC
### Describe the bug

I have a mouse and keyboard, when I play the latest version of Pojavlauncher and I use Minecraft version 1.21 my cursor can't move, I think it's because Pojavlauncher doesn't support it, but the keyboard can still be used

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15944391/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start the Pojav Pojav launcher
2. Play with 1.21 version
3. In game, i play in multiplayer and singleplayer
4. When i move the mouse, kursor can't moving
```

### Expected Behavior

I hope this mouse bug can be fixed quickly

### Platform

```markdown
- Device model: Oppo
- CPU architecture: kryo 260
- Android version: 13
- PojavLauncher version: foxglove-2024621-332de88-v3_openjdk
```

**Comment by Sahariasamadsoyad** [comment] 2024-06-23 16:55
I Have Same Problem!!

**Comment by GaucovyAero** [comment] 2024-06-24 08:09
duplicate of #5648

**Closed as not planned by GaucovyAero** 2024-06-24 08:09 UTC
Labels: bug

**Comment by Zenzctf** [comment] 2024-06-28 09:37
I have the same problem 🥺 @artdeell
