### ISSUE TITLE
[F-Req] <Resolution scaler to changer.>

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#5755] opened 2024-07-06 03:03 UTC
### Is this request related to a bug?

No

### Describe the request.

![Untitled8_20240706100058](https://github.com/PojavLauncherTeam/PojavLauncher/assets/143271606/8c703e6f-7677-4c49-9b1c-c1907a8b178f)
Instead of adjusting the resolution via percentage, adjust the resolution arbitrarily, entering it with data that the user can edit. The code can give some algorithm to automatically adjust the screen ratio so that its fit with the phone.

**Comment by Mathias-Boulay** [comment] 2024-09-11 16:38
Honestly, another system will probably be put in place to address player with GUI sizing issues.

**Comment by GaucovyAero** [comment] 2024-12-29 16:06
duplicate of #4317

**Closed as not planned by GaucovyAero** 2024-12-29 16:06 UTC
Labels: enhancement, worth considering
