### ISSUE TITLE
[BUG] Java 21 (aarch32) bugs

### ISSUE THREAD

**Issue by Cube5x59999** [PojavLauncherTeam/PojavLauncher#5477] opened 2024-05-21 05:38 UTC
### Describe the bug

I have downloaded java 21 for Minecraft 1.20.6, but there's a weird issue where the background paranoma wouldn't load and in-game the textures wouldn't load. I later found out it was a Java 21 specific feature as I tried Java 21 with 1.20.4, which works fine with Java 17.

### The log file and images/videos

Latest log
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15384926/latestlog.txt)

Images of missing paranoma
![Screenshot_20240521-104658_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/98256780/114f8989-b688-4e72-bd2a-f4decb849227)

### Steps To Reproduce

```markdown
1. Set Java 21 ad default
2. Play Minecraft 1.20.4+ (haven't tested any lower)
3. Wait for menu
4. Done
```

### Expected Behavior

I expected it to work normally, as with Java 17 and 1.20.4

### Platform

```markdown
- Device model: Samsung Galaxy Tab A
- CPU architecture: armv8l
- Android version: 11
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

The Java 21 runtime environment used
[jre21-aarch32.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/15384977/jre21-aarch32.zip)

*Also tried JDK 21*

**Comment by aaaapai** [comment] 2024-05-24 14:56
![Screenshot_20240524-225219](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89151134/01c9edee-05d8-41aa-915f-57ba10b7bd49)
My mobile phone doesn't have this problem.It was running in JRE22 at that time.

**Comment by aaaapai** [comment] 2024-05-24 14:57
![Screenshot_20240524-225219](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89151134/01c9edee-05d8-41aa-915f-57ba10b7bd49)
My mobile phone doesn't have this problem.It was running in JRE22 at that time.

**Comment by Cube5x59999** [comment] 2024-05-26 04:50
> It was running in JRE22 at that time.

there's no JRE22.

**Comment by aaaapai** [comment] 2024-05-26 08:11
> > It was running in JRE22 at that time.
> 
> there's no JRE22.

You are right. But it's in my repository.
[jre22-aarch64](https://github.com/aaaapai/android-openjdk-build/actions/runs/9202328033/artifacts/1529630334)
I didn't build JRE22 for aarch32.But you can try using JRE21.0.4
[jre21-aarch32](https://github.com/Vera-Firefly/android-openjdk-autobuild/actions/runs/9202720565/artifacts/1529774393)

**Comment by Cube5x59999** [comment] 2024-05-26 09:50
> > > It was running in JRE22 at that time.
> > 
> > 
> > there's no JRE22.
> 
> You are right. But it's in my repository. [jre22-aarch64](https://github.com/aaaapai/android-openjdk-build/actions/runs/9202328033/artifacts/1529630334) I didn't build JRE22 for aarch32.But you can try using JRE21.0.4 [jre21-aarch32](https://github.com/Vera-Firefly/android-openjdk-autobuild/actions/runs/9202720565/artifacts/1529774393)

I used that exact jre 21 version which is causing the issue
edit : i think the arm 32 version has this problem.

**Comment by Janjack9618** [comment] 2024-06-15 10:52
I still can't fix it

> ### Mô tả lỗi
> Tôi đã tải xuống java 21 cho Minecraft 1.20.6, nhưng có một vấn đề kỳ lạ là hiện tượng hoang tưởng nền không tải được và họa tiết trong trò chơi không tải được. Sau này tôi phát hiện ra đó là một tính năng dành riêng cho Java 21 khi tôi dùng thử Java 21 với 1.20.4, tính năng này hoạt động tốt với Java 17.
> 
> ### Tệp nhật ký và hình ảnh/video
> Nhật ký mới nhất [mới nhấtlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/15384926/latestlog.txt)
> 
> Hình ảnh chứng hoang tưởng mất tích ![Ảnh chụp màn hình_20240521-104658_PojavLauncher (Phiên bản Minecraft Java dành cho Android)](https://private-user-images.githubusercontent.com/98256780/332294552-114f8989-b688-4e72-bd2a-f4decb849227.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDg0NzYsIm5iZiI6MTcxODQ0ODE3NiwicGF0aCI6Ii85ODI1Njc4MC8zMzIyOTQ1NTItMTE0Zjg5ODktYjY4OC00ZTcyLWJkMmEtZjRkZWNiODQ5MjI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEwNDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MzVlNWZiZGNjOTVjYjliZGVkYzY2NmNmOGJjMjI1MjgzNjU2ZGZhOWFiZTlkYTgzNmRjMjk4MmVkZTYyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7pPbogKLmzxx7MYRoHHCyqcQvh063nQ7bd86DC1pxSc)
> 
> ### Các bước để tái tạo
> ```
> 1. Set Java 21 ad default
> 2. Play Minecraft 1.20.4+ (haven't tested any lower)
> 3. Wait for menu
> 4. Done
> ```
> 
> ### Hành vi dự kiến
> Tôi đã mong đợi nó hoạt động bình thường, như với Java 17 và 1.20.4
> 
> ### Nền tảng
> ```
> - Device model: Samsung Galaxy Tab A
> - CPU architecture: armv8l
> - Android version: 11
> - PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
> ```
> 
> ### Còn gì nữa không?
> Môi trường thời gian chạy Java 21 được sử dụng [jre21-aarch32.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/15384977/jre21-aarch32.zip)
> 
> _Cũng đã thử JDK 21_

**Comment by GaucovyAero** [comment] 2024-06-15 11:08
mojang stopped supporting 32-bit devices as of 1.21

**Comment by GaucovyAero** [comment] 2024-06-15 11:09
keeping as wontfix for now, there might be a patch later

**Comment by Janjack9618** [comment] 2024-06-16 14:55
> mojang ngừng hỗ trợ các thiết bị 32 bit kể từ 1.21

oh no how sad I found out about this :((((

**Comment by Janjack9618** [comment] 2024-06-16 14:57
When you get the patch, can you let me know about it?

**Comment by GaucovyAero** [comment] 2024-06-16 15:26
> When you get the patch, can you let me know about it?

it might never come to be honest

**Comment by Cube5x59999** [comment] 2024-06-29 12:46
> > When you get the patch, can you let me know about it?
> 
> it might never come to be honest

hmmm, i just learnt my cpu is 64 bit, but os is 32, _possible?_

edit: if there was ability to bypass incompatible architecture error, I would have tried aarch64

**Comment by Kingblu14** [comment] 2024-07-04 04:23
Is 1.21 not compatible with 3ram and 32rom? Cuz I try every 21 runtime and the panorama is missing and it keeps crashing when I loaded a world

**Comment by Cube5x59999** [comment] 2024-07-10 16:31
> Is 1.21 not compatible with 3ram and 32rom? Cuz I try every 21 runtime and the panorama is missing and it keeps crashing when I loaded a world

not for 32 bit
but my cpu is 64, Android is 32

**Comment by Merith-TK** [comment] 2024-07-20 15:02
> > > When you get the patch, can you let me know about it?
> > 
> > it might never come to be honest
> 
> hmmm, i just learnt my cpu is 64 bit, but os is 32, _possible?_
> 
> edit: if there was ability to bypass incompatible architecture error, I would have tried aarch64

Not without either using a custom rom for your device, or creating and maintaining 64bit libraries for your device.

The problem is that manufacturers will ship an 32bit is with 64bit hardware so they can ship a peice-of-shit 64bit cpu, that performs at 32bit, so they can say its 64bit as its technically not a lie.

**Comment by DonutEpicuS** [comment] 2024-07-25 22:28
i get this bug too, but if i want to join a world/server, it doesn't load

**Comment by Cube5x59999** [comment] 2024-08-27 09:49
> creating and maintaining 64bit libraries for your device.

how? can you explain how can I do this?

**Comment by Merith-TK** [comment] 2024-08-28 21:10
if you dont know what I mean by that, then you dont

This is not some elitist point of view or something, you would need indepth knowledge of java, C, and linux build tools

**Closed as not planned** 2024-09-15 22:29 UTC
Labels: bug, wontfix, known issue
