### ISSUE TITLE
[BUG] how do i fix this

### ISSUE THREAD

**Issue by nooo00000** [PojavLauncherTeam/PojavLauncher#5825] opened 2024-07-20 19:12 UTC
### Describe the bug

tools and food are blank blocks are black

### The log file and images/videos

![Screenshot 2024-07-20 3 11 15 PM](https://github.com/user-attachments/assets/e2e10883-e51c-4bee-a375-81b836dbe320)

### Steps To Reproduce

```markdown
happens when i just start my world normaly
```

### Expected Behavior

pls answers 

### Platform

```markdown
- Device model:chromebook 11 
- CPU architecture: 
- Android version: 11
- PojavLauncher version:foxglove-20240709-045018f-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-07-21 07:35
duplicate of #5674

**Closed as not planned by GaucovyAero** 2024-07-21 07:35 UTC
Labels: bug
