### ISSUE TITLE
Error light

### ISSUE THREAD

**Issue by Hoanpojavlauncher** [PojavLauncherTeam/PojavLauncher#5726] opened 2024-07-02 10:51 UTC
### Describe the bug

The light so much brightness 

### The log file and images/videos

Lastestlog:
[latestlog.txt](https://github.com/user-attachments/files/16066866/latestlog.txt)
Picture 
![1000031842](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139622169/f66333af-a326-49fd-a1b7-8e47f7e62782)

### Steps To Reproduce

```markdown
1.download lastest version 
2.download 1.21 and enter game
3 join a world
3 meet a cave thật like the picture
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: Oppo Reno 3 
- CPU architecture: arm64
- Android version: ColorOs 12
- PojavLauncher version: lastest ver
```

### Anything else?

And it happens on all versions and renders

**Comment by Hoanpojavlauncher** [comment] 2024-07-02 10:52
Omg wrong picture sorry
![Screenshot_2024-07-02-17-19-04-31_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139622169/b3712d94-fffe-4b18-be83-5f68164d91d7)

**Comment by GaucovyAero** [comment] 2024-07-03 15:55
duplicate of #5646

**Closed as not planned by GaucovyAero** 2024-07-03 15:55 UTC
Labels: bug
