### ISSUE TITLE
[BUG] <Unable to create target directory>

### ISSUE THREAD

**Issue by riaddair** [PojavLauncherTeam/PojavLauncher#5927] opened 2024-08-11 15:26 UTC
### Describe the bug

I wanted to download fabric 1.16.5 and it say unable to create target directory 
java.io.IOException: Unable to create target directory
	at net.kdt.pojavlaunch.utils.FileUtils.ensureDirectory(FileUtils.java:59)
	at net.kdt.pojavlaunch.modloaders.FabriclikeDownloadTask.runCatching(FabriclikeDownloadTask.java:57)
	at net.kdt.pojavlaunch.modloaders.FabriclikeDownloadTask.run(FabriclikeDownloadTask.java:37)
	at java.lang.Thread.run(Thread.java:923)

### The log file and images/videos

There is no log file bc i download it now

### Steps To Reproduce

```markdown
1.starting pojav launcher 
2.click download fabric 1.16.5
3.getting "Unable to create target directory" error
```

### Expected Behavior

Download had to start

### Platform

```markdown
- Device model: realme c25y 
- CPU architecture: arm64-v8a
- Android version: 11
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-08-11 15:26
show video

**Comment by riaddair** [comment] 2024-08-11 15:28
Uploading XRecorder_11082024_192811.mp4…

**Comment by riaddair** [comment] 2024-08-11 15:29
> show video


https://github.com/user-attachments/assets/e67babdc-dfd3-43c5-b76f-7f68c9ce7b30

**Comment by riaddair** [comment] 2024-08-11 15:34
> show video

And there no log file i have 1 log file and it is 0 byte

**Comment by riaddair** [comment] 2024-08-11 15:37
Pls help anyone i couldn't find anything about it

**Comment by GaucovyAero** [comment] 2024-08-14 06:29
cannot reproduce, closing

**Closed as not planned by GaucovyAero** 2024-08-14 06:29 UTC
Labels: bug, invalid, fill the template

**Comment by Redresso2** [comment] 2025-02-07 07:42
The "Unable to create target directory" error in PojavLauncher, usually occurs due to permission issues, low storage space, or some problem with the settings of the launcher

Try this:
Enabling all the permissions of Pojav launcher
Deleting some files to free up storage
Change all the settings of your launcher back to default settings
