### ISSUE TITLE
[BUG] <when i finished all 1.17 playing process its not opening. No problem with other versions>

### ISSUE THREAD

**Issue by Farajullah1992** [PojavLauncherTeam/PojavLauncher#1774] opened 2021-08-03 05:44 UTC
### Describe the bug

java.lang.NullPointerException: println needs a message
	at android.util.Log.println_native(Native Method)
	at android.util.Log.i(Log.java:179)
	at net.kdt.pojavlaunch.utils.V117CompatUtil.getTexturePackList(V117CompatUtil.java:82)
	at net.kdt.pojavlaunch.utils.V117CompatUtil.runCheck(V117CompatUtil.java:105)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:123)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
Hhhhhhh
```

### Expected Behavior

I expected the game launches 

### Platform

```markdown
- Device model: redmi note 9 pro max
- CPU architecture:aarch64 
- Android version: 11
- PojavLauncher version: version 3.3.1.1
```

**Comment by artdeell** [comment] 2021-08-03 05:49
Full version not listed.

**Comment by khanhduytran0** [comment] 2021-08-04 06:40
Duplicate of #1738

**Closed as completed by khanhduytran0** 2021-08-04 06:40 UTC
Labels: bug, duplicate
