### ISSUE TITLE
Mouse problem

### ISSUE THREAD

**Issue by ZeNon0q** [PojavLauncherTeam/PojavLauncher#5588] opened 2024-06-14 16:15 UTC
### Describe the bug

When I updated my Android 13 to 14 there's something wrong with the mouse cuz I can only click the menu on the left side but I can't click anything on the right side using my mouse, how can I fix this?? 

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/172835539/e8d29d4f-9743-4477-a5cf-02398167675e

Here I'm trying to click on the right side but I can't but I can only click the left side. 

### Steps To Reproduce

```markdown
?
```

### Expected Behavior

I hope there's anyway I can fix this if somebody know how to pls tell me

### Platform

```markdown
- Device model: infinix
- CPU architecture: 
- Android version: 14
- PojavLauncher version:edelweiss-20230928-9484d0c-v3_o penjdk
```

### Anything else?

How can I fix this?

**Comment by GaucovyAero** [comment] 2024-06-14 18:52
duplicate of #5000, please mention your exact device model in that issue

**Closed as not planned by GaucovyAero** 2024-06-14 18:52 UTC
Labels: bug
