### ISSUE TITLE
[BUG] New Update 

### ISSUE THREAD

**Issue by Zack694** [PojavLauncherTeam/PojavLauncher#5691] opened 2024-06-27 09:39 UTC
### Describe the bug

New Update Crashes my game instantly when I click on play. It's not my device problem. It's the new update problem, and it's not my mods either. So please fix it

### The log file and images/videos
 
[latestlog.txt](https://github.com/user-attachments/files/16014933/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open Pojavlauncher 
2. Click *Play*
3. Crashes for no reason
```

### Expected Behavior

Crashes for no reason

### Platform

```markdown
- Device model: vivo 1906
- CPU architecture: idk
- Android version: Android 11
- PojavLauncher version: Latest (New Update)
```

**Comment by Jasnopi77GG** [comment] 2024-06-27 09:57
Its same like me

**Comment by GaucovyAero** [comment] 2024-06-27 12:18
wrong log, send latestlog.txt

**Comment by Zack694** [comment] 2024-06-27 13:41
> wrong log, send latestlog.txt

Sorry, here: 
[latestlog.txt](https://github.com/user-attachments/files/16014933/latestlog.txt)

**Comment by Unknown795** [comment] 2024-06-27 14:13
Yeah I've tried so many times but everytime I take a look at the latest log on the logs folder and open the text, it's always the same.

**Comment by Unknown795** [comment] 2024-06-27 14:23
I think it's the Zink renderer, because it's the only renderer out of the three that doesn't work. It doesn't open Minecraft on all versions of the game.

https://github.com/PojavLauncherTeam/PojavLauncher/assets/173440970/a266628d-23f1-423c-902d-463c7f97dad9

**Comment by Unknown795** [comment] 2024-06-27 14:24
Here is the latest log file I had after trying to launch the game on the video.
[latest.log](https://github.com/user-attachments/files/16015563/latest.log)

**Comment by GaucovyAero** [comment] 2024-06-27 15:45
duplicate of #5657, try updating your java runtime by using one from android-openjdk-build-multiarch

**Closed as not planned by GaucovyAero** 2024-06-27 15:45 UTC
Labels: bug, invalid, NO_LOG, fill the template
