### ISSUE TITLE
Add import modpack from local file.

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#5898] opened 2024-08-03 02:57 UTC
### Is this request related to a bug?

No.

### Describe the request.

Some modpack makers don't release the modpacks on Causeforge/Modrinth,i hope you can add "Inport modpack from local file".

### Anything else?

No.

**Comment by CowSheep72** [comment] 2024-08-03 09:29
duplicate of #5555

**Closed as not planned** 2024-08-03 11:24 UTC
Labels: enhancement
