### ISSUE TITLE
Pixelmon Texture Issues

### ISSUE THREAD

**Issue by sreyaspopz** [PojavLauncherTeam/PojavLauncher#1638] opened 2021-07-08 03:48 UTC
I installed pixelmon mod and it so lag and texture was very bugy. But I installed shaderpack that fixed but the fps18-21 That's so bad please fix it. 

1. Start PojavLauncher
2. Load modpack 
3. texture  bug

**Platform:**
 - Device Model [ Mi 8 Pro 8/128]
 - CPU architecture [ aarch64] 
 - Android Version [ 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6781307/latestlog.txt)

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment] 2021-07-08 03:49
Duplicate of #1584. *possibility ripped the default template*

**Comment by khanhduytran0** [comment] 2021-07-08 03:50
Duplicate of #1584

**Closed as completed by khanhduytran0** 2021-07-08 03:49 UTC
Labels: bug, duplicate

**Comment by khanhduytran0** [comment] 2021-07-08 03:51
*just don't expect any mobile GPU has 10GB VRAM as RTX 3080*

**Comment by sreyaspopz** [comment] 2021-07-08 03:52
Yaa thanks😔
