### ISSUE TITLE
Can't play 1.18, 1.18 optfine

### ISSUE THREAD

**Issue by balamurugan116** [PojavLauncherTeam/PojavLauncher#2635] opened 2022-01-28 09:27 UTC
### Describe the bug

It just crashes

### The log file and images/videos

Latest log:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7957327/latestlog.txt)

### Steps To Reproduce

```markdown
Start pojav lancher
Create a world 
100% loaded
Instantly crashes
```

### Expected Behavior

To load the world

### Platform

```markdown
- Device model: SM-M025F (a02qins)
- CPU architecture: AArch64 Processor rev 4 (aarch64)
- Android version: R(11)
- PojavLauncher version: 
Latest 2nd versison
```

### Anything else?

I all ready posted a bug but the solution does not work

**Comment by khanhduytran0** [comment] 2022-01-28 11:19
You may want to try disabling cloud rendering.

**Comment by saputraGTX** [comment] 2022-05-22 04:53
https://github.com/saputraGTX/docs/pull/3#issuecomment-1133817754

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:28
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:28 UTC
Labels: bug
