### ISSUE TITLE
[BUG] cant launch game without network even if the version was downloaded

### ISSUE THREAD

**Issue by Silvigarabis** [PojavLauncherTeam/PojavLauncher#5194] opened 2024-03-03 22:09 UTC
### Describe the bug

if you try to launch game with no Internet connection, it will fail.
Regardless of whether the version has been downloaded, it always download the 'gamemeta' at launch, if it's not success, it can't be launched.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/73000464/3b636d22-0a00-4860-99d7-6b05a02767b7

the video performed following test:
- **00:00** launch normally, with good network, succeed 
- **00:51** launch with no Internet connection, failed 
- **01:09** just check settings, found `Check libraries after downloading` and `Verify game version manifest` already *disabled*, `Game download source` set to `Default`
- **01:30** launch with no Internet connection again, failed 
- **01:38** connect to the internet, and launch again, succeed 

### Steps To Reproduce

```markdown
(see the video description)
```

### Expected Behavior

Installed versions can be started without a network connection

### Platform

```markdown
- Device model: Huawei DUB-AL00
- CPU architecture: arm64
- Android version: 8.1.0
- PojavLauncher version: edelweiss-20240219-195568c-v3_openjdk
```

**Comment by GaucovyAero** [comment] 2024-03-03 23:27
cannot reproduce, works fine on the same build as you

**Comment by GaucovyAero** [comment] 2024-03-10 07:50
reopening, this happens on Forge for me


https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/d5b46e6a-de7e-4705-aa6c-408b5fe40eb9

**Comment by Silvigarabis** [comment] 2024-03-10 08:08
> reopening, this happens on Forge for me
> 
>  recording_20240310_084939.mp4

I sorry, but maybe it's cause by #5195 ?
or there's other reasons caused cant launch forge?

I have only tested vanilla version in this issue, and it only appears when I turned `Verify game version manifest` off, so I commented #5195 and didn't try to reopen this issue.

**Comment by GaucovyAero** [comment] 2024-03-10 08:26
probably caused by #5195 but ima close this as a duplicate issue then, i forgot there was another one

**Closed as not planned by GaucovyAero** 2024-03-10 08:26 UTC
Labels: bug
