### ISSUE TITLE
[BUG] PojavLauncher closes out after pressing play.

### ISSUE THREAD

**Issue by backupwaffles1** [PojavLauncherTeam/PojavLauncher#5654] opened 2024-06-23 01:31 UTC
### Describe the bug

Whenever I try to play the game on my Chromebook, the application will shut down after I press play. It doesn't have a chance to load up. I've reinstalled Pojavlauncher multiple times and the problem still hasn't fixed.

### The log file and images/videos

[Screen recording 2024-06-22 9.18.39 PM.webm](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173582348/db5d80c4-8c26-413e-a6de-e184d9744347)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher on Chromebook
2. Select Your Version and Press Play
3. Wait until the buttons show up.
4. Boom, shows a white screen then crashes.
```

### Expected Behavior

I expected the game to load up as normal.

### Platform

```markdown
- Device model: Chromebook
- CPU architecture: ARM64
- Android version: ???
- PojavLauncher version: foxglove-20240621-332de88-v3_openjdk
```

### Anything else?

Take your time, no pressure.

**Comment by backupwaffles1** [comment] 2024-06-23 01:33
Side Note: I tried again after reallocating the memory and the problem still happened. So changing the memory allocation did not help.

**Comment by GaucovyAero** [comment] 2024-06-24 08:00
send log

**Comment by GaucovyAero** [comment] 2024-06-24 20:36
closing as a duplicate of #5511

**Closed by GaucovyAero** 2024-06-24 20:36 UTC
Labels: bug, invalid, NO_LOG, fill the template, device-specific
