### ISSUE TITLE
[BUG] mouse aint supported on samsung a12 bruh

### ISSUE THREAD

**Issue by Nanify69** [PojavLauncherTeam/PojavLauncher#1615] opened 2021-07-03 10:48 UTC
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
A clear and concise description of what the bug is 

Mouse wont move and its just stuck 

**Add a log file if you want to see your bug fixed !**

https://pastebin.com/jtxShh4r

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Samsung galaxy a12 6/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210321 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment] 2021-07-03 10:49
@Nanify69 fill the template or this issue will be closed.

**Comment by Nanify69** [comment] 2021-07-03 10:51
@khanhduytran0 Ok hold on

**Comment by khanhduytran0** [comment] 2021-07-03 11:18
It's known issue

**Comment by khanhduytran0** [comment] 2021-07-03 11:19
Duplicate of #1235

**Closed as completed by khanhduytran0** 2021-07-03 11:19 UTC
Labels: bug, duplicate

**Comment by Nanify69** [comment] 2021-07-03 11:38
@khanhduytran0 but is there anyway to fix the bug?

**Comment by Nanify69** [comment] 2021-07-03 23:52
Btw hope u guys fix it also screen wont move lol

**Comment by khanhduytran0** [comment] 2021-07-03 23:53
I have no idea right now :despair:
