### ISSUE TITLE
[BUG] Minecraft 24w34a

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#6031] opened 2024-09-06 06:17 UTC
### Describe the bug

Minecraft Snapshot 24w34a Black Screen In Holy Gl4ES Render Even Though Shader Dump Is Enabled

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16903695/latestlog.txt)

![Screenshot_20240906_131245](https://github.com/user-attachments/assets/6c58aa14-004d-48a0-995d-f05c05bafefd)

### Steps To Reproduce

```markdown
Install Minecraft Snapshot 24w34a
```

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

There isn't any

**Comment by GaucovyAero** [comment] 2024-09-06 08:43
shader dump literally does nothing, it just puts all the shader code into your log file, closing as a duplicate of #5968

**Closed by GaucovyAero** 2024-09-06 08:43 UTC
Labels: bug
