### ISSUE TITLE
It keeps logging me off

### ISSUE THREAD

**Issue by crimemannn** [PojavLauncherTeam/PojavLauncher#1709] opened 2021-07-22 09:16 UTC
### Describe the bug

When I join the game it emedietly says exited game then it logs me off the app 
Help

### The log file and images/videos

Game exited

### Steps To Reproduce

```markdown
Play the game
```

### Expected Behavior

Playing the game

### Platform

```markdown
- Android version:
```

**Comment by khanhduytran0** [comment] 2021-07-22 09:23
Closing as invalid as the form wasn’t filled properly.

**Closed as completed by khanhduytran0** 2021-07-22 09:23 UTC
Labels: bug, invalid, NO_LOG, fill the template

**Comment by crimemannn** [comment] 2021-07-22 09:27
> Closing as invalid as the form wasn’t filled properly.

How am I supposed to fill that basically it logs me off like what do you want me to say

**Comment by khanhduytran0** [comment] 2021-07-22 09:27
We don’t even know what device are you using. We don’t have an automatic log uploader aswell.

**Comment by khanhduytran0** [comment] 2021-07-22 09:29
> ### Platform
> - Android version:

**Comment by crimemannn** [comment] 2021-07-22 09:29
What is even an automatic log aploader and I deleted all other platform in the report than android wich is the platform

**Comment by khanhduytran0** [comment] 2021-07-22 09:31
You still don’t understand? Where are
- phone model?
- RAM amount?
- latestlog.txt?

**Comment by khanhduytran0** [comment] 2021-07-22 09:31
Also, we don’t own your device to simply reproduce `Play the game` step.

**Comment by khanhduytran0** [comment] 2021-07-22 09:32
The information being given is not enough for us. *we don’t own your device*

**Comment by khanhduytran0** [comment] 2021-07-22 09:35
You didn’t even give information about which Minecraft version you have tried, ~~do we have to spend 69420 years to test on every device, every Android version, every launcher version and every Minecraft version just for you?~~
Looks like you are trying to play 1.17(.1)/1.18, [follow this if it’s what you want](https://pojavlauncherteam.github.io/updates/117.html).
