### ISSUE TITLE
[BUG] Mode "Mouse pass" flaw

### ISSUE THREAD

**Issue by Sumrak-Sumarokov** [PojavLauncherTeam/PojavLauncher#2221] opened 2021-11-09 10:51 UTC
### Describe the bug

Mode "Mouse pass" stop working after you touch hotbar

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/7504069/latest.log)

[bug](https://imgur.com/a/g5kfQyc) 

### Steps To Reproduce

```markdown
1. Start PojavLauncher 
2. Open world or connect to server
3. Touch any hotbar slot
4. Try to slid pressed button with mode "mouss pass"
```

### Expected Behavior

It's just should working properly

### Platform

```markdown
- Device model: Pocophone F1 6/64g
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: crocus-105-f26df7edb-v3_openjdk
```

### Anything else?

Bruh

**Comment by Mathias-Boulay** [comment] 2021-11-10 06:59
Thanks for the input, it is indeed an unintended behavior

**Comment by Mathias-Boulay** [comment] 2021-11-11 23:46
@SumrakSumarokov I dropped the Controls revision 2.5 on the v3_openjdk branch.
Can you try to reproduce the problem ?

**Comment by Mathias-Boulay** [comment] 2021-11-14 21:35
The flaw is fixed in the commit I just made, closing the issue

**Closed as completed by Mathias-Boulay** 2021-11-14 21:35 UTC
Labels: bug
