### ISSUE TITLE
[BUG] cant play with 1.20.1 fabric loader 0.15.11 

### ISSUE THREAD

**Issue by Jasnopi77GG** [PojavLauncherTeam/PojavLauncher#5690] opened 2024-06-26 18:33 UTC
### Describe the bug

Cant play pojaf launcher 1.20.1 fabric loader 0.15.11

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/15993776/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojaf launcher 
2. Instal fabric loader 1.20.1
```

### Expected Behavior

before everything worked normally when pojaf was updated to the new version when i tried to play pojaf the launcher strangely crashed even though before it wasn't like that

### Platform

```markdown
- Device model:Galaxy A11
- CPU architecture:
- Android version:12 
- PojavLauncher version:1.20.1 fabric loader 0.15.11
```

### Anything else?
Fix it please

**Comment by GaucovyAero** [comment] 2024-06-26 19:09
duplicate of #5657

**Closed as not planned by GaucovyAero** 2024-06-26 19:09 UTC
Labels: bug
