### ISSUE TITLE
Auto exit

### ISSUE THREAD

**Issue by saurabhris** [PojavLauncherTeam/PojavLauncher#2677] opened 2022-02-04 01:12 UTC
### Describe the bug

Game automatically exited when play server and  graphics is black.

### The log file and images/videos

Game automatically exited when play server and  graphics is black.

### Steps To Reproduce

```markdown
Game automatically exited when play server and  graphics is black.
```

### Expected Behavior

Game automatically exited when play server and  graphics is black.

### Platform

```markdown
- Device model: iqz3
- CPU architecture: snapdragon 768
- Android version: 11
- PojavLauncher version: play store
```

**Comment by NotAHero04** [comment] 2022-02-04 02:43
Please send the log file.

**Comment by NotAHero04** [comment] 2022-02-04 02:43
also a duplicate of #2676

**Comment by khanhduytran0** [comment] 2022-02-06 06:09
> also a duplicate of #2676

~~Looks like his submit issue button is messed up~~

**Comment by khanhduytran0** [comment] 2022-02-06 06:10
"Game automatically exited when play server and graphics is black" is not a valid log file.
"Game automatically exited when play server and  graphics is black" is not valid steps to reproduce.

**Closed as completed by khanhduytran0** 2022-02-06 06:10 UTC
Labels: bug, invalid, fill the template
