### ISSUE TITLE
[BUG] <Fabric 1.17.1 Crash>

### ISSUE THREAD

**Issue by Hadbrinenotcool** [PojavLauncherTeam/PojavLauncher#2599] opened 2022-01-22 08:25 UTC
### Describe the bug

Crash...what you expect?

### The log file and images/videos

>   da log
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7917908/latestlog.txt)
`

### Steps To Reproduce

```markdown
1.Enter Pojav
2.Installed Fabric 0.12.9
3.Put some Sodium,Phosphor,Lithium Mods
4.Set the renderer to zink and Runtime to 17
5.Play
6.Application exited with code 1
```

### Expected Behavior

i expect the game to launch

### Platform

```markdown
- Device model:Oppo A71/3GB
- CPU architecture: Arm64
- Android version: 7.1.1
- PojavLauncher version: Lastest Release
```

### Anything else?

Help fix!!

**Comment by Hadbrinenotcool** [comment] 2022-01-22 08:33
Woops i meant

> ### Describe the bug
> Crash...what you expect?
> 
> ### The log file and images/videos
> > da log
> > [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7917908/latestlog.txt)
> > `
> 
> ### Steps To Reproduce
> ```gfm
> 1.Enter Pojav
> 2.Installed Fabric 0.12.9
> 3.Put some Sodium,Phosphor,Lithium Mods
> 4.Set the renderer to zink and Runtime to 17
> 5.Play
> 6.Application exited with code 1
> ```
> 
> ### Expected Behavior
> i expect the game to launch
> 
> ### Platform
> ```gfm
> - Device model:Oppo A71/3GB
> - CPU architecture: Arm64
> - Android version: 7.1.1
> - PojavLauncher version: Lastest Release
> ```
> 
> ### Anything else?
> Help fix!!

Woops i mean 0.12.12 and that logs was yesterday lols!
Here the recent one
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7917922/latestlog.txt)

**Comment by khanhduytran0** [comment] 2022-01-22 08:35
Well, there’s no point for it. You’re using a slow renderer and try to optimize framerate from it...

**Comment by khanhduytran0** [comment] 2022-01-22 08:37
So, it somehow fails to load OSMesa. Try using the latest build with virglrenderer instead.

**Comment by Hadbrinenotcool** [comment] 2022-01-22 09:28
> So, it somehow fails to load OSMesa. Try using the latest build with virglrenderer instead.

Ight ima try

**Comment by Hadbrinenotcool** [comment] 2022-01-22 09:47
> So, it somehow fails to load OSMesa. Try using the latest build with virglrenderer instead.

Its crash

**Comment by Hadbrinenotcool** [comment] 2022-01-22 09:50
> Well, there’s no point for it. You’re using a slow renderer and try to optimize framerate from it...

I mean, how am i suppose to play 1.17.1 when i got 2-7 fps?

**Comment by khanhduytran0** [comment] 2022-01-22 09:53
> I mean, how am i suppose to play 1.17.1 when i got 2-7 fps?

Was it what you got with gl4es? If not, think again.

**Comment by Hadbrinenotcool** [comment] 2022-01-22 17:33
> > I mean, how am i suppose to play 1.17.1 when i got 2-7 fps?
> 
> Was it what you got with gl4es? If not, think again.

No no it was the zink, the Gl4es able to load in (but cant get in world) while zink itself just crash as soon the loading started

**Comment by Hadbrinenotcool** [comment] 2022-01-22 17:34
In Vanilla i got 10-20 fps (2 render distance&Flat World) while Fabric (without sodium) i got 1-5 fps

**Comment by Hadbrinenotcool** [comment] 2022-01-22 17:35
> In Vanilla i got 10-20 fps (2 render distance&Flat World) while Fabric (without sodium) i got 1-5 fps

Note: i used Gl4es 1.1.5 3.2 due zink kept crashing on current version

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:18
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:18 UTC
Labels: bug
