### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by saurabhris** [PojavLauncherTeam/PojavLauncher#2690] opened 2022-02-06 05:15 UTC
### Describe the bug

When I play minecraft with optifine but exit the game at few moments

### The log file and images/videos

When I play minecraft with optifine but exit the game at few moments

### Steps To Reproduce

```markdown
1. Pls solve my problem When I play minecraft with optifine but exit the game at few moments
```

### Expected Behavior

When I play minecraft with optifine but exit the game at few moments

### Platform

```markdown
- Device model: iq z3

- CPU architecture: SD 768G
- Android version: 11
- PojavLauncher version: play store
```

### Anything else?

When I play minecraft with optifine but exit the game at few moments

**Comment by khanhduytran0** [comment] 2022-02-06 06:11
Please fix your submit issue button first, thanks.

**Comment by khanhduytran0** [comment] 2022-02-06 06:11
Duplicate of #2689

**Closed as completed by khanhduytran0** 2022-02-06 06:11 UTC
Labels: bug, duplicate, invalid, fill the template
