### ISSUE TITLE
Physical mouse not working[BUG] <Short description>

### ISSUE THREAD

**Issue by Oppvirtual** [PojavLauncherTeam/PojavLauncher#5678] opened 2024-06-25 16:03 UTC
### Describe the bug

When I connect physical mouse and launche the game it is not working freezes in the centre

### The log file and images/videos

Freezes physical mouse 

### Steps To Reproduce

```markdown
Start launcher
And tap on play button 
Physical mouse freezes in centre
```

### Expected Behavior

Solve

### Platform

```markdown
- Device model: redmi note 8 pro
- CPU architecture: arm64 
- Android version: 11
- Launcher version: play store version
```

### Anything else?

Solve the problem

**Comment by GaucovyAero** [comment] 2024-06-25 16:50
duplicate of #5648

**Closed as not planned by GaucovyAero** 2024-06-25 16:50 UTC
Labels: bug

**Comment by ZombieSPie** [comment] 2024-07-17 05:21
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9584072517
