### ISSUE TITLE
Cape not working.

### ISSUE THREAD

**Issue by RainbowyGuy** [PojavLauncherTeam/PojavLauncher#6269] opened 2024-11-13 18:18 UTC
### Describe the bug

There should be a cape whenever I launch Minecraft with optifine and every setting for comsetica and capes turned on.

### The log file and images/videos

![Screenshot_20241113_200653_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/7ad82e85-408a-475f-acef-c4395f9d908d)
![Screenshot_20241113_200639_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/36efee23-db5f-4be3-9bbe-39b3ad800ff3)
![Screenshot_20241113_200218_Opera](https://github.com/user-attachments/assets/0f1dad61-ef91-471d-b872-2756ea0cd5b3)
![Screenshot_20241113_200623_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/3ef8647b-af48-4e8d-b7a2-e4b49e7cb35b)

### Steps To Reproduce

```markdown
1. open cosmetica on web browser
2. Add cape/cosmetics
3. Turn every setting on for capes (in cosmetica, pojavlauncher and in optifine)
4. Open the game and get in a world/server
```

### Expected Behavior

A cape I added in cosmetica should show up using optifine.

### Platform

```markdown
- Device model: Samsung Galaxy A14
- CPU: Mediatek MT6769 Helio G80
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

I have a legitimate Minecraft account.

**Comment by GaucovyAero** [comment] 2024-11-25 20:55
duplicate of #5379

**Closed as not planned by GaucovyAero** 2024-11-25 20:55 UTC
Labels: bug
