### ISSUE TITLE
[BUG] Custom Control Key Combo Box Slippable Mapping Error

### ISSUE THREAD

**Issue by XiaoMingGame2023** [PojavLauncherTeam/PojavLauncher#4975] opened 2023-12-24 09:54 UTC
### Describe the bug

Use the combo box and make a slide button that can still be triggered by moving the screen after the combo box is closed, causing a false touch

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/135619465/d861d320-ba3c-4500-982a-a0d93b524335

### Steps To Reproduce

```markdown
Create a combo box and add multiple slide buttons, enter the game and use the combo box, close when finished, Triggered when a key is pressed and slid
```

### Expected Behavior

There will be no such contact

### Platform

```markdown
Redmi Note12 turbo（POCO F5） Android13 MIUI14.0.25 edelweiss-20231221-5f39dd7-rep/bytehook
```

### Anything else?

Hope to fix as soon as possible, this problem is very affecting the user experience

**Comment by GaucovyAero** [comment] 2024-06-12 07:47
duplicate of #4628

**Closed as not planned by GaucovyAero** 2024-06-12 07:47 UTC
Labels: bug, duplicate, known issue, needs fixing

**Comment by Felix14-v2** [comment] 2024-06-28 13:53
> Hope to fix as soon as possible, this problem is very affecting the user experience

Actually this may be extremely useful if you use this behavior in the right way
https://github.com/PojavLauncherTeam/PojavLauncher/issues/4628#issuecomment-1732699980
