### ISSUE TITLE
[BUG] Fatal error in v3.3.1

### ISSUE THREAD

**Issue by KostyanSigaev** [PojavLauncherTeam/PojavLauncher#633] opened 2021-01-17 15:42 UTC
New version and new bugs...
Error in video: https://m.youtube.com/watch?v=VFJ_vviv_Rw
Error in log:
I/jrelog  ( 7710):     ERROR MESSAGE:
I/jrelog  ( 7710): 
I/jrelog  ( 7710):         SoundSystem did not load after 30 seconds.
I/jrelog  ( 7710): 
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave1.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave10.ogg
I/jrelog  ( 7710): 
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave11.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave12.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave13.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave2.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave3.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave4.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave5.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave6.ogg
I/jrelog  ( 7710): 
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave7.ogg
I/jrelog  ( 7710): 
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave8.ogg
I/jrelog  ( 7710): 
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave9.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)
I/jrelog  ( 7710): 
I/jrelog  ( 7710): java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/weather/rain1.ogg
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
I/jrelog  ( 7710): 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
I/jrelog  ( 7710): 	at java.net.URL.openStream(URL.java:1068)
I/jrelog  ( 7710): 	at ng.a(SourceFile:104)
I/jrelog  ( 7710): 	at ng.a(SourceFile:93)
I/jrelog  ( 7710): 	at ng.run(SourceFile:42)

**Comment by khanhduytran0** [comment] 2021-01-18 04:51
About UI, press F11 in custom keycode to fix.
About log, it just fail attempt to download audio, since classic resources moved to other places.

**Comment by Mathias-Boulay** [comment] 2021-06-04 17:43
Issue not reproducible on google play release.
Closing issue.

**Closed as completed by Mathias-Boulay** 2021-06-04 17:43 UTC
Labels: bug
