### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by RiptideTheDice** [PojavLauncherTeam/PojavLauncher#5890] opened 2024-07-31 03:10 UTC
### Describe the bug

This bug is making my key stay hold until i pressed another key.
Also, when i press "T" or "/" to open the chat, it type in another t or / in the chat box.
And Every. Single. Time. This bug happens when I start Pojavlauncher, Please help

### The log file and images/videos

sss
![download - 2024-07-30T143208 793](https://github.com/user-attachments/assets/4bf753c1-765b-43ee-90c7-8274df5fb67c)

### Steps To Reproduce

```markdown
1. Start 1.21
2. Join Any Multiplayer Server
3. It always happens to me
```

### Expected Behavior

help

### Platform

```markdown
- Device model:Google Octopus
- CPU architecture:3  3
- Android version:3 
- PojavLauncher version:3
```

### Anything else?

sa

**Comment by GaucovyAero** [comment] 2024-07-31 07:13
duplicate of #4469

**Closed as not planned by GaucovyAero** 2024-07-31 07:13 UTC
Labels: bug

**Comment by RiptideTheDice** [comment] 2024-08-03 00:28
> duplicate of #4469

alr but how fix it?? cuz I had same problem
