### ISSUE TITLE
[BUG] <Short description>Wierd mouse moving 

### ISSUE THREAD

**Issue by Chesper31** [PojavLauncherTeam/PojavLauncher#5946] opened 2024-08-16 17:56 UTC
### Describe the bug

When i use my mouse in other games everything works perfect,but in pojav launcher it's very slippery and unplayable 

https://github.com/user-attachments/assets/fc95d6e9-b4d5-4510-9a2f-2dc820c6206a

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16640160/latestlog.txt)

### Steps To Reproduce

```markdown
1.connect the mouse and keyboard
2.pick a version
3.launch the game
4.move the mouse
```

### Expected Behavior

I expected my mouse to move smooth,i installed pocked edition minecraft and there everything it's normal,but on pojav the cirsor is very slippery and woerd even if i change the sensivty 

### Platform

```markdown
- Device model: pocox3 pro
- CPU architecture: arm64 i think
- Android version: 13
- PojavLauncher version: leatest
```

**Comment by GaucovyAero** [comment] 2024-08-16 20:39
duplicate of https://github.com/PojavLauncherTeam/PojavLauncher/issues/5647 and #5945, try lowering your polling rate

**Closed as not planned by GaucovyAero** 2024-08-16 20:39 UTC
Labels: bug

**Comment by Chesper31** [comment] 2024-08-16 23:30
> duplicate of #5647 and #5945, try lowering your polling rate

I will try this,but can you be more specific and tell me how to do it? 👍 😄

**Comment by GaucovyAero** [comment] 2024-08-16 23:37
> > duplicate of #5647 and #5945, try lowering your polling rate
> 
> I will try this,but can you be more specific and tell me how to do it? 👍 😄

no, every mouse has it different and some mouse brands might not even give the possibility to do so

**Comment by Chesper31** [comment] 2024-08-17 00:14
> > > duplicate of #5647 and #5945, try lowering your polling rate
> > 
> > 
> > I will try this,but can you be more specific and tell me how to do it? 👍 😄
> 
> no, every mouse has it different and some mouse brands might not even give the possibility to do so

Thanks,i found how to change it in mouse control panel,i changed from 1000hz to 125hz i will try it and annonce u if it worcks.

**Comment by GaucovyAero** [comment] 2024-08-17 02:02
nice

**Comment by Chesper31** [comment] 2024-08-17 17:40
> nice

I lowered the polling rate,it worked for a day and now the issue came back,i lowered it again but sems to doesn't worck anymore.any idea?

**Comment by Chesper31** [comment] 2024-08-17 17:48
> > nice
> 
> I lowered the polling rate,it worked for a day and now the issue came back,i lowered it again but sems to doesn't worck anymore.any idea?

I saw thath every time when i click my sens just increase for a bit and it's very weird
