### ISSUE TITLE
[F-REQ]I think the operation of the buttons is a bit bad.

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1679] opened 2021-07-16 05:28 UTC
If I press a key (such as W) for a long time and move to another key (such as S) without letting go, then the game will still keep the behavior of the first key (the character will move forward instead of backward).It's easy to have problems, just like this video.

https://user-images.githubusercontent.com/77053726/125896272-5adea544-6556-4abc-83e0-9e217df66511.mp4

Can we design a decision mechanism for keyboard movement or key modification like minecraft bedrock edition?

**Comment by khanhduytran0** [comment] 2021-07-16 05:29
- fill the template

**Comment by khanhduytran0** [comment] 2021-07-16 05:29
Duplicate of #1647

**Closed as completed by khanhduytran0** 2021-07-16 05:29 UTC
Labels: duplicate, enhancement, fill the template

**Comment by khanhduytran0** [comment] 2021-07-16 06:35
Also, it’s not a problem, it’s how button works.
