### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Eishe17** [PojavLauncherTeam/PojavLauncher#1962] opened 2021-09-03 10:12 UTC
### Describe the bug

Labymod installer 1.16.5 vanilla has problems I see all the black icons.  and then in vanilla Minecraft I see the eggs all the same colorb (black and white) the banners are all white and the experience is all white

### Steps To Reproduce

```markdown
1 start pojav Launcher
2 grab a banner, egg and you will notice that they are not real Minecraft colors
```

### Expected Behavior

I expected the game to go like normal but then I noticed some colors were WRONG

### Platform

```markdown
- Device model: Redmi not 9 pro 
- CPU architecture: .
- Android version: 11
- PojavLauncher version: 3.3.1.1
```

**Comment by khanhduytran0** [comment] 2021-09-03 11:42
Duplicate of #1902

**Closed as completed by khanhduytran0** 2021-09-03 11:42 UTC
Labels: bug, duplicate
