### ISSUE TITLE
[BUG] Black Screen For Oppo reno3 1.12.2

### ISSUE THREAD

**Issue by Iyanryzcut** [PojavLauncherTeam/PojavLauncher#4727] opened 2023-10-12 08:26 UTC
### Describe the bug

The bug is black screen with Gl4es and mod Mclib Get black screen after mojang screen 1.12.2 forge + optifine

### The log file and images/videos
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12888455/latest.log)

### Steps To Reproduce

```markdown
1.start pojav
2.Using Gl4es render
3.Install 1.12.2
4.Install forge
5.Using Blockbuster mod,Optifine,mclib mod,metamorph
6.Black screen without any code
```

### Expected Behavior

When I run the launcher, when the Mojang screen comes out, after that it's a black screen and there's no code whatsoever

### Platform

```markdown
- Device model: OPPO RENO3/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: [Latest]
```

### Anything else?

Black screen when using 1.12.2 forge with optifine | Gl4es render | with blockbuster.mod

**Comment by Iyanryzcut** [comment] 2023-10-12 08:27
Please fix these

**Comment by GaucovyAero** [comment] 2023-10-12 12:32
send latestlog.txt

**Comment by Iyanryzcut** [comment] 2023-10-13 01:21
Ples fix
It

**Comment by GaucovyAero** [comment] 2023-10-13 05:43
> Ples fix It

nobody knows what the issue is if you dont send the log, closing

**Closed as not planned by GaucovyAero** 2023-10-13 05:43 UTC
Labels: bug, invalid, NO_LOG
