### ISSUE TITLE
Tittle Screen bug

### ISSUE THREAD

**Issue by BottomotPH29** [PojavLauncherTeam/PojavLauncher#2588] opened 2022-01-20 04:51 UTC
### Describe the bug

Hey can you fix the title screen all, when I play the world the screen back to normal plsss help

### The log file and images/videos

![Screenshot_20220120-122737_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/82305152/150275593-f38cf388-780d-4789-b967-dc303f9cc6e6.jpg)

### Steps To Reproduce

```markdown
Tittle screen bug
```

### Expected Behavior

Tittle screen bug

### Platform

```markdown
- Device model: Galaxy A12 
- CPU architecture: Aarch64
- Android version: 11
- PojavLauncher version: 1.12.2 forge
```

### Anything else?

Tittle screen bug

**Comment by SprainedSpark89** [comment] 2022-01-26 20:45
try turning off the mods or use 1.12.2 no forge
and what version of pojavlauncher like debug play store or action build

**Comment by BottomotPH29** [comment] 2022-01-28 15:47
Debug

**Comment by SprainedSpark89** [comment] 2022-01-28 17:20
use play store you can install debug or playstore at the sametime.

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:20
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:20 UTC
Labels: bug
