### ISSUE TITLE
When playing 1.18, game crashes.

### ISSUE THREAD

**Issue by Fance1** [PojavLauncherTeam/PojavLauncher#2656] opened 2022-01-31 04:56 UTC
### Describe the bug

I was trying to play 1.18, but when i started, it loaded, it crashed. The crash log says "Shader overlay." I'm just trying to play a server with friends...

### The log file and images/videos

>  @`
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7968182/latestlog.txt)
`

### Steps To Reproduce

```markdown
Open pojavlauncher. Select 1.18, press play, wait to load.
```

### Expected Behavior

I expected the game to play 

### Platform

```markdown
- Device model: Samsung Galaxy S9
- CPU architecture: aarch64
- Android version:  11
- PojavLauncher version: latest version
```

**Comment by Fance1** [comment] 2022-01-31 05:44
Sadness

**Comment by Mathias-Boulay** [comment] 2022-05-23 22:31
The issue is fixed on the release candidate build.

**Closed as completed by Mathias-Boulay** 2022-05-23 22:31 UTC
Labels: bug
