### ISSUE TITLE
[BUG] SCREEN MESS UP!(1.12.2)

### ISSUE THREAD

**Issue by Adam0530** [PojavLauncherTeam/PojavLauncher#589] opened 2021-01-09 16:15 UTC
So the bug is everytime I am opening inventory, pause, crafting or make any gui appear in my screen the screen will be mess up when I am closing the gui... Like I am aiming to the downside and when I close the gui and then tap the screen... My aiming automatically aiming to the upside fastly.. It happen everytime and everyday I play on minecraft 1.12.2( I have not any other version then 1.12.2 but I did try it on 1.16 and it does not had this bug

**Platform:**
 - Device Model [Vivo y17]
 - CPU architecture [aarch64]
 - Android Version [9]

**Comment by Dimon245** [comment] 2021-01-09 18:39
[this bug (4.5)](https://github.com/PojavLauncherTeam/PojavLauncher/issues/576) actually does happen on the latest version, but not as often. It is more likely to happen if you use an external mouse though

**Comment by khanhduytran0** [comment] 2021-01-20 21:59
Get [latest build](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/498877588)

**Comment by Mathias-Boulay** [comment] 2021-06-04 15:47
The issue is gone and not present on the google play release, closing issue.

**Closed as completed by Mathias-Boulay** 2021-06-04 15:47 UTC
Labels: bug
