### ISSUE TITLE
[BUG] Mouse sensitivity lagging

### ISSUE THREAD

**Issue by PadMadoff** [PojavLauncherTeam/PojavLauncher#1703] opened 2021-07-20 18:29 UTC
### Describe the bug

In video

### The log file and images/videos

[Mouse bug video](https://youtu.be/3nAIJtrDCBI) 

### Steps To Reproduce

```markdown
1. Starting Pojav Launcher with connected mouse and keyboard.
2. Go into my world.
3. Mouse bug.
```

### Expected Behavior

I hoped the mouse sensitivity would be the same as if I swiped my finger across the screen.

### Platform

```markdown
- Device model: POCO X3 NFC
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release
```

**Comment by khanhduytran0** [comment] 2021-07-20 23:07
Duplicate of #1227

**Closed as completed by khanhduytran0** 2021-07-20 23:07 UTC
Labels: bug, duplicate
